### ISSUE TITLE
To be able to decided wich fields are available

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#100]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [X] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To have options in the settings page for the activation or deactivatio of the different chapters metafields 

### Feature Use Case

Some publishers we do not need some of those fields. It will simplify the page (and it will load faster the page mayb).

I would like to have control to any fields the authors must write. So i can decide wich fields are or are not available.

### Other Notes

![captura de pantalla 2018-07-01 a las 20 32 40](https://user-images.githubusercontent.com/3929177/42137537-320421be-7d6e-11e8-86dd-9ed9d8f82351.png)

**Comment by SteelWagstaff** [comment]
Won't implement
