### ISSUE TITLE
Short title as admin book title

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#101]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [X] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

We use the title of the book as book name in book cover, also in the chapter page. Besides front end options, we can see in the admin area as book name in two different places

![captura de pantalla 2018-07-02 09 03 10](https://user-images.githubusercontent.com/3929177/42149563-08f3e34a-7dd7-11e8-9ee8-989df1736840.png)

Instead of book title, we could use the short title as admin catalog titles

### Feature Use Case

Some times the title is too long and is not possible to reade it.

### Other Notes

![captura de pantalla 2018-07-02 09 02 34](https://user-images.githubusercontent.com/3929177/42149622-3a8edb3a-7dd7-11e8-8747-632c1df3b27b.png)

**Comment by SteelWagstaff** [comment]
Won't implement
