### ISSUE TITLE
Admin area titles are static

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#102]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [x] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To be able to read along all the books we have acces.

### Feature Use Case

Some times we have dozens of books but is not possible to do scroll down as the book names are static. We can not see more books than those. I have 100 books but I just can see 40 with a big screen. around 20 maybe in my laptop

### Other Notes

![captura de pantalla 2018-07-02 09 10 56](https://user-images.githubusercontent.com/3929177/42149781-d73083bc-7dd7-11e8-97a4-5efa50f1336b.png)

**Comment by SteelWagstaff** [comment]
Sample solution (using jQuery): https://css-tricks.com/long-dropdowns-solution/

**Comment by SteelWagstaff** [comment]
Dropdown now supports scrolling. Closing as completed.
