### ISSUE TITLE
To deactivate the PB plugin in selected sites

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#103]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [X] Integration with third-party services

### Feature Description

As superadmin to be able to deactivate the plugin in selected sites. So the sub-site of the multisite would be an original wordpress site

### Feature Use Case

Some times we need to have complements to the books. In that way, we could do it. Like to have different catalogs, or personal sites for the authors or ... integrated in the same network.

Imagine, we have 2 types of sites. One for theory and other for exercises. After the registration, the user can create one type of site or the other.

**Comment by greatislander** [comment]
Sorry, this goes against the way we've built Pressbooks from day one and we won't be adding it to our roadmap.
