### ISSUE TITLE
consistency in part and chapter settings (show in ...)

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#106]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [x] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To have the same flexibility in the parts as in the chapters. So I could show or not the content of the part, or to export or not as simple as I do with the chapters

### Feature Use Case

Some times we have different requeriments, so it could be more flexible

### Other Notes
![captura de pantalla 2018-07-13 a las 16 49 24](https://user-images.githubusercontent.com/3929177/42698197-779894dc-86bd-11e8-9cde-cb7d9026d47e.png)

**Comment by SteelWagstaff** [comment]
@colomet you can select/unselect all chapters in a part by clicking the show in web/show in export headers at present. Closing this issue.
