### ISSUE TITLE
bulk edition of chapters and parts

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#107]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [x] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

Some times we require a fast editing of a post and chapter. Or a Bulk edition of the post and chapters. Both wodpress core functionalities are can be very useful.

### Feature Use Case

if we have to edit many chapters or post at once or just a quick editing of some of them

### Other Notes

![captura de pantalla 2018-07-13 a las 17 03 22](https://user-images.githubusercontent.com/3929177/42698661-dcb80f4a-86be-11e8-9971-707c52e28625.png)

and 

![captura de pantalla 2018-07-13 a las 17 05 49](https://user-images.githubusercontent.com/3929177/42698726-08839cde-86bf-11e8-8ba8-701b93b873c2.png)

instead of

![captura de pantalla 2018-07-13 a las 17 05 04](https://user-images.githubusercontent.com/3929177/42698693-edc4c1c0-86be-11e8-9541-00880b3b7479.png)

**Comment by SteelWagstaff** [comment]
See also #122.

**Comment by SteelWagstaff** [comment]
Closing as duplicate exists in form of #122
