### ISSUE TITLE
Clone books description

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#108]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [x] Book themes
- [ ] Integration with third-party services

### Feature Description

To change from cloned to update or modified or ...

### Feature Use Case

Cloned is a technical term. Maybe we could have a more user friendly name for that

### Other Notes

![captura de pantalla 2018-07-16 11 47 33](https://user-images.githubusercontent.com/3929177/42754045-4b3b377c-88f3-11e8-8fd7-ca7fd481decd.png)

**Comment by SteelWagstaff** [comment]
Closing as we don't have any plans to change the verbiage here at present. Thank you for the suggestion, though.
