### ISSUE TITLE
Remove parts (including front/back matter) from sidebar TOC if they're empty

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#112]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [X] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

If a section have no content, maybe we can deleted from the table of contents

### Other Notes

![captura de pantalla 2018-07-19 15 09 23](https://user-images.githubusercontent.com/3929177/42944408-de169f04-8b65-11e8-829b-4f3c1eb77713.png)

**Comment by SteelWagstaff** [comment]
Won't fix
