### ISSUE TITLE
Create uniform citations across content types

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/ideas#118]
### Feature Scope

- [ ] Accessibility and inclusivity
- [x] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [x] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

With the newly created licensing and attribution for images, we may need to create similar citations for other types of media.

- embedded content (youtube videos)
- previously shared text/content

### Feature Use Case

Make a core, uniform citation manager that can make uniform outputs with the new image citations. Could be the core answer to "Candela Citations"

### Other Notes

<img width="970" alt="screen shot 2018-07-25 at 6 21 37 pm" src="https://user-images.githubusercontent.com/29982981/43231068-c5583e32-9038-11e8-8ad3-72993afed3af.png">

**Comment by SteelWagstaff** [comment]
Lumen Learning added this functionality with a citations plugin: https://github.com/lumenlearning/candela-citation, which I believe was initially written by @jgraham909 and may now be maintained by @monkecheese?

**Comment by SteelWagstaff** [comment]
Related to https://github.com/pressbooks/ideas/issues/223

**Comment by NMSalmon** [comment]
Has this feature idea gotten any additional traction? This would be an amazing improvement!

**Comment by SteelWagstaff** [comment]
We had initial conversations with Lumen Learning about their funding our development of a potential replacement for their Candela Citations plugin, but they ended up going a different direction. It's in our backlog but we don't have any immediate plans to build this feature. Hope we're able to get to it before too long -- it's really a great idea.

**Comment by SteelWagstaff** [comment]
Closing in favor of #223
