### ISSUE TITLE
Twitter Share remove default handle of  @pressbook

### ISSUE THREAD

**Issue by johnpeterm** [pressbooks/ideas#119]
### Feature Scope
When user click twitter share button of the book, by default pressbook  handle @pressbooks appears instead of the handle of the installed domain.
![0](https://user-images.githubusercontent.com/20897821/43527186-9ef36b14-95c3-11e8-82d9-fce1841d44f1.png)

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

**Comment by greatislander** [comment]
@johnpeterm Where would we find out the handle of the installed domain?

**Comment by johnpeterm** [comment]
In this book click on the twitter  share button, you will see the share details
http://books.manarkeni.com/illakiyamkandakavalar/

**Comment by greatislander** [comment]
No, what I mean is: if you want `@pressbooks` to be replaced with `@your-twitter-handle`, where do we get the Twitter handle to use instead of `@pressbooks`? Do you expect that there would be a book setting for this?

**Comment by johnpeterm** [comment]
I would just prefer the book title and the url of the book in the twitter post, may be we can ignore the @your-twitter-handle

**Comment by colomet** [comment]
as we have the # in Book info, maybe to use the # instead of the @.

**Comment by colomet** [comment]
https://github.com/pressbooks/ideas/issues/111

**Comment by SteelWagstaff** [comment]
Removed the automatic `@pressbooks` from X share post, as Pressbooks no longer actively maintains a twitter presence. Users can add new `@` to post messages as desired.
