### ISSUE TITLE
On FB Share default pressbook image appears on pop up window

### ISSUE THREAD

**Issue by johnpeterm** [pressbooks/ideas#120]
### Feature Scope
When you click on the FB share button, on the pop up share window, the cover image is of default pressbook, but when you share the right cover image is shared.

On the Pop up window
![100](https://user-images.githubusercontent.com/20897821/43528809-74fb50d4-95c7-11e8-9700-4a74caafbb9b.png)

When the book is shared, the right image appears
![101](https://user-images.githubusercontent.com/20897821/43528833-831dab44-95c7-11e8-95cf-002b32b6ea71.png)

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

**Comment by greatislander** [comment]
This is a problem with Facebook, not Pressbooks.
