### ISSUE TITLE
API for cloned books connection

### ISSUE THREAD

**Issue by danzhik** [pressbooks/ideas#124]
### Feature Scope

- [x] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [x] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

Force websites, which cloned book, to send some sort of ping/trace to original book website.

### Feature Use Case

This feature can be useful not only for copyright issues (I mean to make it possible for authors to see if the one who cloned book follows terms of use), but also for references of translations/modifications, which authors of original content can find useful. This feature will provide bidirectional bound between books, not single direction like now (cloned book -> original book).

### Other Notes

Of course tracebacks and pingbacks can be used somehow for this purpose, but I believe that it will make more vulnarabilities than profits in terms of this case. If you think this feature can be really useful, I can try to make sort of prototype for this system, so that you could probably use it.

**Comment by greatislander** [comment]
@danzhik This is an interesting idea. We were discussing using [WebMentions](https://alistapart.com/article/webmentions-enabling-better-communication-on-the-internet) for this. I think we need to discuss how this would work from a UX perspective a bit more before it makes sense to start any work on it, but I'll follow up with you.

**Comment by danzhik** [comment]
@greatislander, great, then let me know when you will have time to talk about it, I will try to help as much as I can

**Comment by SteelWagstaff** [comment]
Something along these lines was included in https://github.com/pressbooks/pressbooks/releases/tag/6.6.0. See https://github.com/pressbooks/pressbooks/issues/3055 and https://github.com/pressbooks/pressbooks/issues/3057 for details.
