### ISSUE TITLE
private book allow the preview of the cover page

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#128]
### Feature Description

If a book is private, we see a warming:
![captura de pantalla 2018-09-12 a las 10 08 46](https://user-images.githubusercontent.com/3929177/45411188-dec8dc80-b673-11e8-81dd-b815d740838e.png)

https://open.books4languages.com/english-a1-grammar-es/

but maybe is better to show the cover page with a warming there.

### Feature Use Case

If we are working with a book, and is not finish, we can share the link and advertise before the publication, or if the people find the book, instead of an close page, they will find a description about what we are working with...

### Other Notes

I have so many working books and i like to start to make the promotion before are finish, so in that way the day is finish the book, all is ready. Now, if somebody open the promotion link, find a empty page, if we have the book cover available, they will understand is not ready because we are working with.

**Comment by greatislander** [comment]
Hi @colomet — this is a good idea. I guess in practice you could partially achieve this right now by making the book public by hiding all chapters from the web by unchecking "Show in Web" on the organize page. However, that's not a perfect solution and I think this is a valuable use case for us to address.

**Comment by SteelWagstaff** [comment]
Interesting idea, but hasn't come up often in last 5 years, so closing for now.
