### ISSUE TITLE
Protect content copy paste

### ISSUE THREAD

**Issue by johnpeterm** [pressbooks/ideas#129]
### Feature Description

The author will give permission for copy paste content of the webbook. If the author wants his webbook be protected from copy paste, by selecting protect webbook content, the content should be protected.
![opera snapshot_2018-09-14_150748_support scribd com](https://user-images.githubusercontent.com/20897821/45542701-42980480-b830-11e8-85a6-db9dd6f65132.png)

### Feature Use Case

Since pressbook is one of the best tool for open publishing, there are times the author likes his content be protected and wants his book be read from the webbook url. This feature may help the author to protect the content to an certain level.

Like to see this feature in pressbook core, may be below the "Webbook Options" soon.

**Comment by greatislander** [comment]
You can probably use something like [this](https://css-tricks.com/copy-paste-the-web/#article-header-id-3) in Custom Styles to disable copy/paste from your webbook. However, I don't think we will be adding this to Pressbooks core. Modifying the default text behaviour (e.g. preventing selection) is frustrating to users and probably has implications for assistive technology.

**Comment by johnpeterm** [comment]
Thank you @greatislander this is helpful

**Comment by johnpeterm** [comment]
Just a suggestion, Copy paste protection CSS code by default put in the custom styles, but comes with those code commented. Those who want to enable the copy paste protection can uncomment it from the custom styles options. This may be much easier way to enable copy past protection for those who want to have this option. 

Advantages may be
Standardized code which is tested with the theme
Easy for non tech people to enable it
