### ISSUE TITLE
Search Page: to be able to choose the number of results

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#13]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [x] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

Wordpress have a way to choose the number of resoults and posts of a page. Maybe we can give acces

![captura de pantalla 2018-03-08 a las 20 40 55](https://user-images.githubusercontent.com/3929177/37172498-3da519fe-2311-11e8-9853-ce12bb1e4b58.png)

### Feature Use Case

the search bar is really important for educational books. In the future, with the metadata, the search bar would be much more powerful. A first step is to allow to have the configuration of the resoults.

**Comment by SteelWagstaff** [comment]
Won't implement.
