### ISSUE TITLE
"Clone" individual pages to a new book via an Admin page and the API

### ISSUE THREAD

**Issue by ghost** [pressbooks/ideas#139]
### Feature Description

As an admin, I can "clone" individual pages from a book into a new book from an admin page.
As a developer, I can use the WP or PB API to "clone" individual pages from a book into a new book.

### Feature Use Case

This has a number of uses, but specifically for us, it would allow anyone interested in adopting content to teach from to more easily remix and reuse content on a more granular level than cloning an entire book.  It is also probably a less computationally expensive task to clone individual pages than to clone the entirety of a books contents.

### Other Notes

A conversation on this topic has been started in Pressbooks discourse.  I'm not sure if this is the right place to link to it, but am happy to link and tag anyone here who have expressed interest in this feature.

**Comment by SteelWagstaff** [comment]
See discourse conversation on this topic at https://pressbooks.community/t/cloning-individual-book-pages/698/12

**Comment by SteelWagstaff** [comment]
This can be done via the import from HTML option and weblink to a Pressbooks book (within the target book).
