### ISSUE TITLE
pressbooks book widgets

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#14]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [x] Book themes
- [ ] Integration with third-party services

### Feature Description

We need to have widgets as a way to be able to use our code.

### Feature Use Case

To have an independent section in the theme will allow us to create our own specific tools without destroy the theme by and update.

**Comment by colomet** [comment]
I just read widgets would be remplace by gutenberg

**Comment by colomet** [comment]
https://discourse.pressbooks.org/t/widgets-in-books/61

**Comment by SteelWagstaff** [comment]
@colomet Closing this as we won't be adding this anytime soon to Pressbooks core. Thanks for the suggestion, though!
