### ISSUE TITLE
Provide more opt-in or opt-out options for comment notification emails

### ISSUE THREAD

**Issue by NMSalmon** [pressbooks/ideas#144]
### Feature Description

It would be great to be able to opt people in and out of "new comment" moderation emails independent of their roles as editors/administrators in the text.

From the user's perspective, one approach would be to set this up as an opt in/out option everyone could control for themselves (and others?) in the users page. 

**Example:**

![comment moderation checkbox](https://user-images.githubusercontent.com/35341860/47819300-0e1cd100-dd28-11e8-81f7-5e004ba5244d.png)

It would also be neat to have the option to add additional, non-PB-affiliated email addresses that could receive comment moderation email notifications. (Some users might want to set up a separate email account specifically to field comments, answer questions about the text, and hold conversations with future contributors. It would be redundant to give these email addresses an entirely new Pressbooks persona, but it might be desirable for that address to be the primary place for the team to receive comment-related mail nonetheless.)

### Feature Use Case

At present, it's my understanding that anyone who is an administrator (and possibly also editors, subscribers, etc?) receives a notification email whenever a comment is posted to a Pressbooks text. For teams that are made up of multiple people, it sometimes happens that even people who need administrator privileges in their role as authors/maintainers of the book don't actually have a reason to receive moderation emails. It could be useful for them to be able to decide whether they get the extra mail.

**Comment by SteelWagstaff** [comment]
Won't fix. We've essentially killed commenting as a Pressbooks feature.
