### ISSUE TITLE
Previous part and next part arrows in admin page

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#146]
### Feature Description

As with the chapters, to have the arros in admin page that chage between parts

### Feature Use Case

if parts have to be modify.

### Other Notes

![captura de pantalla 2018-11-02 a las 21 27 25](https://user-images.githubusercontent.com/3929177/47939013-1d497d80-dee6-11e8-8f3a-d002a113ae4c.png)
![captura de pantalla 2018-11-02 a las 21 25 41](https://user-images.githubusercontent.com/3929177/47939000-11f65200-dee6-11e8-90ac-511a4de47502.png)

**Comment by SteelWagstaff** [comment]
Won't implement
