### ISSUE TITLE
Delete links to media attachment pages in PDF export

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#148]
### Feature Description

If we export  the books, we have the links and previews in the pdf. but we may whant to not have those links in the pdf or ebook, just text, and to have the web book with digital complements.

### Feature Use Case

if the book is printed as a complement of the site, people know in the site much more possibilities are available.

**Comment by SteelWagstaff** [comment]
You can suppress these with custom CSS. Closing as 'won't fix'
