### ISSUE TITLE
Reset a book

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#150]
### Feature Description

To be able to reset a book to the original stage

### Feature Use Case

Some times we have a book, we modify as we are starting with pressbooks and we do not likes how looks like, so with the option, we could to have a clean start.

**Comment by SteelWagstaff** [comment]
@colomet Closing issue as super admins can currently delete a book and create a new book with that URL, or change an existing book's URL and use the old URL for a newly created book. Both of these seem to me to accomplish what you're asking about with this 'feature request'
