### ISSUE TITLE
Visually distinguish between glossary elements and hyperlinks

### ISSUE THREAD

**Issue by NMSalmon** [pressbooks/ideas#152]
### Feature Description

Visually distinguish between a hyperlinked word and a term with a glossary tooltip attached to it.

### Feature Use Case

Many of the users in our UW-Madison Pressbooks instance will be using the new Glossary tool alongside text that may have hyperlinks embedded in it. Our previous CM Tooltip Glossary plugin tool used a dotted rather than solid line for its own examples.  I'm testing the glossary tool in our dev instance as well and noticed that there isn't currently a visual distinction between texts highlighted as glossary terms with the new tool and a hyperlink.

**Here's an example of the kinds of hyperlinks that already exist in books in our network:**

![hyperlink in a french pressbooks activity](https://user-images.githubusercontent.com/35341860/49045945-26053a80-f198-11e8-8951-e6a721fabf78.png)

**Here's an example of the underline used in the CM tooltip glossary.** 

![tooltip glossary underline](https://user-images.githubusercontent.com/35341860/49046130-b80d4300-f198-11e8-8c84-bd6ccd7c0cb4.png)

### Other Notes

This concern about setting glossary terms and hyperlinks apart may also be relevant to accessibility. If this is the case, it may be that the dotted underline example below may not be visually distinguishiable enough from the hyperlink to be the best option.

**Comment by SteelWagstaff** [comment]
Hi @NMSalmon--I believe that all glossary items are structured as `<a>` elements with a class `tooltip`. This means that you/we could easily target just these elements using their class and style them however you like with CSS. If you wanted to set them as links with dashed rather than solid underlining, as in the example above, you could try adding either of these to your custom styles: 
`.tooltip {text-decoration-style: dotted;}` or `text-decoration-style: dashed;`

**Comment by NMSalmon** [comment]
Thanks, Steel! I'll do so!

**Comment by SteelWagstaff** [comment]
No problem Naomi. Just wanted to note also that this may also be something that Pressbooks addresses directly, so consider this a possibly helpful workaround until any proposed change is implemented.

**Comment by beckej13820** [comment]
I just wanted to bump this request, because that was one of the first things I noticed upon updating.

Thanks for the workaround Steel!
