### ISSUE TITLE
To use Github ideas as a place for sharing modifications of PB

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#16]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To use github ideas as the place where if somebody develop something or find a piece of code that helps somehow, we can save it here. It would make easy for the rest of us to do modifications to PB

### Feature Use Case

Example: The `<!--nextpage-->` helps for the navitation. Not all the users know about that. We write in the forum and then, nobody find again in the future as it will be in lost inside of the comments. But if each time we have a feature with a simple piece of code we write an independen page with a tiny tutorial or info about it, the community can find it really easy an to enhance PB for specifical purposes in our plugin specific code or the child theme.

wp rocket have something simmilar here: https://github.com/wp-media/wp-rocket-helpers (they develop the features as independent plugins, we can do as snippets or ...)

**Comment by greatislander** [comment]
We'll use this instead: https://github.com/pressbooks/snippets/
