### ISSUE TITLE
Be able to change chapter type from the organize page

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/ideas#163]
### Feature Description

The ability to change "chapter type" from the organize page in some way, either with a drop-down or radio in each chapters line or the mass action tool.

### Feature Use Case

I do a lot of cloning and importing Pressbooks books from one network to another and doing PDF exports for faculty. One of the awkward things that can happen is that on the original network they had used an alternative numbering paradigm, but the book imports without a chapter type, so you end up with double numbering in exports.

The typical fix is to go into every chapter, and change chapter type to numberless.

**Comment by SteelWagstaff** [comment]
Great idea @beckej13820! This looks pretty similar to me to #122. I imagine we might be able to roll them up together in a future release?

**Comment by SteelWagstaff** [comment]
Closing in favour of #122
