### ISSUE TITLE
localized versions of book info

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#165]
### Feature Description

To be able to create the book info in more than one language

### Feature Use Case

different speakers could understand what's a book about. 

Normally it would be In the original language of the book and english. So we all can understand what´s a book about without speak the languag of the book.

### Other Notes

https://support.google.com/webmasters/answer/189077?hl=en

https://github.com/pressbooks/ideas/issues/132

https://github.com/pressbooks/ideas/issues/137

**Comment by greatislander** [comment]
Thanks for consolidating this. Certainly, support for multiple languages is a deficiency of WordPress Core. It has been identified as a focus for Gutenberg Phase 3 (or 4? can't remember). There are tradeoffs between holding out for a core methodology and doing something ourselves. Certainly the biggest obstacle to doing something ourselves would be the scope of work required.

One potential approach could be something along this lines of https://wordpress.org/plugins/multisite-language-switcher/

**Comment by colomet** [comment]
I have a system of translations of books: https://open.books4languages.com/english-a1-grammar/

![captura de pantalla 2019-01-08 a las 14 02 23](https://user-images.githubusercontent.com/3929177/50832313-1c9def00-134e-11e9-9e49-340557ec4158.png)

I do no translate pages, I do use different books for different languages.
My sistem works like that: I do write a book, that book is the original book (main language) and later i have to clone the book and to translate the cloned book in a new languag.


About book info, we require to be able to create more than one page of book info, and to asign a laguage to each book info page. 

I think we must not print that information, it will be much simple if is just for web version.

**Comment by greatislander** [comment]
@colomet Your solution is exactly what I'm referencing: one book per language. I don't know why you wouldn't also translate the book information on the cloned books, though. Can you explain?

**Comment by colomet** [comment]
google SEO, to make easy to find the book. 
And to understand what´s about the book.

If the book is in in spanish, if book info is also in english, everybody will be able to understand what´s about the book.
