### ISSUE TITLE
Discourage translate on a page

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/ideas#179]
### Feature Description

For foreign language books, it might be useful to be able to discourage browsers like Google Chrome from translating a page. 

### Feature Use Case

We have several faculty members that are creating Spanish Language textbooks. Unfortunately, their completely spanish book is being translated to english by web browsers. While nothing will stop a dedicated student that is willing to cut and paste information, it would be nice if their browser didn't offer to automatically translate the entire book.

### Other Notes

https://www.w3.org/International/questions/qa-translate-flag

It seems like there is an html attribute that will discourage translation. It would be really nice if that attribute could be associated with the body of the entire page based on a setting in the theme.

Maybe there could be a setting in the book on the theme options page that if checked would add it in sitewide.

**Comment by SteelWagstaff** [comment]
Won't implement for now.
