### ISSUE TITLE
Allow users to change the ‘contact’ link to a different page/URL

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#180]
### Feature Description

Currently, each PB network has a link in on the network and admin footer called `Contact.` This link now has a filter: https://github.com/pressbooks/pressbooks/pull/1464 and a default value of `https://networknamename.pressbooks.pub/#contact`. 

We'd like to give network managers the ability to change this URL to whatever they like, either through Aldine theme options or through whitelabel settings. When new values are entered in the theme settings or whitelabel plugin settings, the `contact` link should be changed in both the admin & general site footer.

**Comment by mcgratay** [comment]
How this feature currently works: 

- if the contact form is active, the Contact footer link directs the user back to the contact form
- if the contact form is inactive, the administrator has the choice to set a Contact Link in the footer
- if the contact form is inactive and the administrator has not inserted a Contact Link, the Contact form directs toward the Network Admin Email set in the Network Settings. This will almost always be ops@pressbooks.com 

If all of the above is expected, then the feature is complete.

**Comment by dac514** [comment]
>  This will almost always be ops@pressbooks.com 

Ok. We'll have to pick something else here....
