### ISSUE TITLE
Display captions before figures and tables (or allow users to adjust positioning)

### ISSUE THREAD

**Issue by apurvaashok** [pressbooks/ideas#182]
### Feature Description

Captions for tables and figures should consistently display above images or tables to better meet accessibility standards. Alternatively, the captions could be easily adjustable in the Theme Options –  display above image, below image, and maybe in the future for certain themes, to the right or left of image.

### Feature Use Case

Currently, table captions display above tables in some formats, but not all. Figure captions consistently appear below images. A tool allowing users to adjust the position of captions (above or below tables/images) would be excellent for better accessibility of Pressbooks books. The feature could be used by anyone creating accessible content using Pressbooks, be it in the educational space or indie-publishing world.

### Other Notes

This feature idea was brought to attention by an accessibility reviewer on an open textbook in the Rebus Press.

**Comment by greatislander** [comment]
Related info:

+ https://www.w3.org/WAI/tutorials/tables/caption-summary/
+ https://www.w3.org/WAI/tutorials/images/complex/

I've never heard of figure captions being positioned above images, for what it's worth; the pattern I've always seen is:

```html
<figure>
  <img alt="A cat" />
  <figcaption>The author's cat.</figcaption>
</figure>
```

I'd be interested in seeing some examples of this in use for reference.

**Comment by apurvaashok** [comment]
Thanks, Ned! There's also a related request about long descriptions: https://github.com/pressbooks/ideas/issues/145

That's the pattern we've seen too, and what is currently in place on Pressbooks books. The accessibility reviewer for one of our books noted that "It has always been my experience that students prefer to have information front loaded; as in this example there would be a preference to have the Figure text information followed by the image. That has been my standard practice" – if this is best practice, then setting this as the default would be good. Else, a feature like what I've described above would be great for any creators wishing to customize how captions are displayed.

**Comment by SteelWagstaff** [comment]
Placing image captions before the image is not a common a11y accomodation that I'm aware of. For authors with different preferences, caption location can be adjusted with CSS on a book by book basis as needed. Closing as 'wont fix' for now.
