### ISSUE TITLE
Allow network managers to manually whitelist iFrame providers

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#186]
### Feature Description

WordPress/Pressbooks is generally quite strict about the kinds and types of iFrames they allow to be embedded in published pages by normal (non-super admin users). We have a strong preference for [discoverable oEmbeds](https://oembed.com/#section4), but not all external content providers use this method. 

However, some of our network managers would like to add other content providers to an approved whitelist of external providers. Rather than serving as the gatekeeper ourselves for all of these requests, I propose that we add a simple whitelist form available to network managers in the current 'network admin' -> 'settings' -> 'sharing & privacy' settings page. 

The form would look and function similarly to the 'Limited Email Registrations' form available to super admins in the 'Network Settings' page currently. Network managers would be given simple instructions and could choose to whitelist either domains, i.e. `www.npr.org` or paths, i.e. `//docs.google.com/` for their network. These domains/paths should be added via filter to the array of whitelistedDomains currently found in https://github.com/pressbooks/pressbooks/blob/dd870c89f7960ed46d364df9cd711f081608f05e/inc/interactive/class-content.php#L24-L32

### Feature Use Case

This would allow network managers to choose to whitelist the embedding of external content from trusted providers by authors with regular permissions to their network. Network managers would then be responsible for deciding what policies/practices they'd like to use re: embedding external content in their webbooks.

**Comment by mcgratay** [comment]
I believe this still needs to be made visible to those with network admin user privileges

**Comment by mcgratay** [comment]
Also still can't prevent an iframe from automatically converting to `[embed]` shortcodes when a chapter is saved

**Comment by mcgratay** [comment]
Resolved
