### ISSUE TITLE
Select "Register My Book Later" by default at user registration

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/ideas#188]
### Feature Description

When users register, they're asked whether they would like to register their book now or later. The "Register my book now" setting is chosen by default. Instead, select the "Register my book later" option, or select no option at all. 

### Feature Use Case

Many books are potentially created that don't serve a purpose for an active project. This can take up storage space and make book administration more difficult.

**Comment by SteelWagstaff** [comment]
Our signup page inherits the WordPress wp-signup.php page. We make some alterations to the text in https://github.com/pressbooks/pressbooks/blob/426b73a48566bc8ec633a64cd31d8b9d80ed18bc/inc/registration/namespace.php#L27-L34. It looks like the decision about the default check box is made here: https://github.com/WordPress/WordPress/blob/b639963d7ab6e55379649a9116b6aa86fd494785/wp-signup.php#L613-L616 & https://github.com/WordPress/WordPress/blob/b639963d7ab6e55379649a9116b6aa86fd494785/wp-signup.php#L565. I think we'd need to override the 'signup_for' value for the `$_POST` to start as `user` to change the default 'register by book later' option? I don't know how easy that would be to do without rewriting/replacing the default signup page.

**Comment by SteelWagstaff** [comment]
Won't fix
