### ISSUE TITLE
Use Mathjax in Webbooks

### ISSUE THREAD

**Issue by dac514** [pressbooks/ideas#189]
When users enter [latex] or other math notation code, we should render in the webbook using MathJax (instead of PB LaTeX).

Todo: Use Mathjax CommonHTML output processor for [latex] expressions or things that start with $$ in webbooks: 

+ Docs: http://docs.mathjax.org/en/latest/output.html#mathjax-output-components
+ For an example implementation, see https://github.com/lumenlearning/pressbooks-mathjax

We want to move towards replacing PB LaTeX entirely (~and possibly even WP Quick LaTeX, unless there are things it does that MathJax can’t do~ Edit: Nope.).  

This is a step towards that goal.

**Comment by dac514** [comment]
Also worth checking out: https://github.com/phillord/mathjax-latex

**Comment by SteelWagstaff** [comment]
Another very simple implementation for WP available at https://github.com/boolesrings/Simple-Mathjax-wordpress-plugin/blob/master/simple-mathjax.php
