### ISSUE TITLE
Allow network managers to set default PDF page size for new books

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#199]
### Feature Description

Network managers can currently set a default theme for new books created on their network. Some users have also indicated that they would like the ability to choose the default PDF export page size ('Theme Settings'->'PDF Options'->'Page Size') for new books on their network as well. The default value for this is currently `Digest (5.5" x 8.5")`. We propose allowing network managers to set a different default value for newly created books on their network. This would be useful for any publisher who regularly produces print books with different known dimensions.

**Comment by mcgratay** [comment]
When a network manager sets a custom height and width, that custom size will affect the network successfully, BUT the Network Defaults page will read that the size has been reverted back to the Pressbooks default: 5.5" x 8.5" 

Find screen recording in Slack.

**Comment by dac514** [comment]
Thanks. Fixed the reported. issue. Please try again.
