### ISSUE TITLE
Match admin page with WordPress roles

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#2]
### Feature Scope

- [ ] Accessibility and inclusivity
- [X] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

Wordpress have several roles:
![captura de pantalla 2018-03-05 a las 14 17 53](https://user-images.githubusercontent.com/3929177/36977032-092970fa-2080-11e8-9570-7b5aa69f4bbf.png)
But the admin page is not conected. Like, if I´m  contributor I can not create a new page, but the screen is there. So, maybe or to make it possible to create a page or to delete the buttoms.

Now, i can not create as contributor a new page from the sidebar
![captura de pantalla 2018-03-05 a las 14 15 41](https://user-images.githubusercontent.com/3929177/36977259-d7b0126c-2080-11e8-9426-42ade42a1ddc.png)

new chapter buttom of the sidebar give me that (not if I do create the page from the top buttom):
![captura de pantalla 2018-03-05 a las 14 23 17](https://user-images.githubusercontent.com/3929177/36977318-014f1dd4-2081-11e8-97e0-0e5eeb6670dd.png)

### Feature Use Case

New users can understand better what to do with a role if what we show have consistency.

**Comment by greatislander** [comment]
@colomet In testing, you can create everything _except_ parts as a contributor. I think there was a historical reason for this; parts affect the structure of a book, and so should only be able to be created by users with a higher level of privileges. We might want to remove the "Add Part" link for contributors to make this clearer, but I think it makes sense.

**Comment by colomet** [comment]
Yes. I see. I think is a good idea, just authors or even editors can create a part. But the link maybe can be removed. For a better understanding of the rights.

**Comment by colomet** [comment]
maybe we can update https://guide.pressbooks.com/chapter/users/ with information about the Part- chapter ...

**Comment by greatislander** [comment]
Closed in favour of https://github.com/pressbooks/pressbooks/issues/1142.
