### ISSUE TITLE
Allow users to see title of book in mobile version of 'my books' page

### ISSUE THREAD

**Issue by NMSalmon** [pressbooks/ideas#201]
### Feature Description

Currently, if I use my iPhone to navigate to the "My Books" admin page in Chrome, I see a list of "show/hide in catalog" options for individual books, but I can't actually see what those books' titles are:

![mobile my books interface pressbooks](https://user-images.githubusercontent.com/35341860/64065053-325a7000-cbce-11e9-83e2-989077d69a23.PNG)

To see the titles, I need to click on the dropdown arrows for each text individually: 
![my books dropdown](https://user-images.githubusercontent.com/35341860/64065054-325a7000-cbce-11e9-964c-5d860de5ca50.jpeg)

I'd prefer it if the title of the book appeared next to the show/hide in catalogue items so that it was easier to navigate directly to the admin page for the text I was interested in tweaking. 

### Feature Use Case

True, most people don't do the bulk of their editing on mobile, but it can be nice to make emergency tweaks on-the-go. This is especially the case for people who are helping others navigate the interface and may need to troubleshoot in a book they have admin privileges for, but don't navigate to regularly. This happens to me not infrequently, and I often don't remember the exact titles or urls for texts. Having to toggle through dropdown arrows on all of the books in my catalogue just to see which is the correct place to click feels inefficient.

**Comment by SteelWagstaff** [comment]
The 'my books' page is not being actively maintained, so I think this one is a 'won't fix'.
