### ISSUE TITLE
Contributor Enhancements for Book Info 

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#202]
Filed on behalf of @PressbooksLiz: 

When a user attempts to leave the author field blank in a PB where there are only editors it defaults to the main person in the book’s PB account. Can’t seem to leave it blank. See https://github.com/pressbooks/ideas/issues/134 for previous discussion of this. If you put 'Edited by `Contributor name` in the Author field to hack the issue, this shows up under the default license info too, e.g. “Media Innovation and Entrepreneurship by Edited by Michelle Ferrier & Elizabeth Mays ”

Would also like to add the ability to reorder contributors. Took me hours to try to re-do all my contributors in alphabetical order in https://press.rebus.community/media-innovation-and-entrepreneurship/.

Also, the system adds commas after everything, as well as a terminal 'and' which isn’t always optimal. E.g. `Research from, and Cheryl Cuillier`: 

Finally, there's no revision history for book info, which means you can't easily revert Book Info in same way as you can with textual content.

Related to https://github.com/pressbooks/ideas/issues/134

**Comment by NMSalmon** [comment]
Yes! This would be a great thing to address!

**Comment by SteelWagstaff** [comment]
Closing in favor of #134
