### ISSUE TITLE
Add open-access typeface that covers more of the Unicode character set

### ISSUE THREAD

**Issue by PressbooksLiz** [pressbooks/ideas#204]
### Feature Description

Many fonts in common usage only support some portion of the Unicode character set. Can Pressbooks add support for the [FreeFonts font family](https://www.gnu.org/software/freefont/), a set of three typefaces (serif, sans serif, and monospace) that aims to provide coverage for as much of the Unicode character set as possible?

### Feature Use Case

Specific characters needed for, say, a music theory book, may not be supported in the default theme used by a given theme. One user reports: 
> We use the unicode for sharp (♯), flat (♭), and natural (♮) symbols frequently in our text, and Times (the default font) renders them poorly. The FreeFont families do a much better job.

**Comment by SteelWagstaff** [comment]
These fonts are released under open licences and can be downloaded here: http://savannah.gnu.org/projects/freefont/ (most recent WOFF files available at http://ftp.gnu.org/gnu/freefont/freefont-woff-20120503.zip and TTF files here: http://ftp.gnu.org/gnu/freefont/freefont-ttf-20120503.zip). If we do host these font on our servers and allow users to use them, we should comply with their [license terms](https://www.gnu.org/software/freefont/FAQ.html).

> **Can I use GNU FreeFont as a Web-Font in my web site, without the site inheriting the GPL?**
> By using a font as a Web-Font, you are in effect distributing the font — to comply with the GPL, its license and contact information must be distributed along with it. So long as that information is delivered to your user, the GPL is satisfied. Your web site does not inherit the GPL by distributing the font. If you use the WOFF format files from the GNU FreeFont distribution, there is no problem, as these contain all the required information.

> **Can I incorporate GNU FreeFont into my GPL-licensed software?**
> If your software is GPL v.3 or later, there is no issue. It would be nice to credit GNU FreeFont somewhere in your documentation.

> **Can I incorporate GNU FreeFont into my (proprietary/non-GPL) software?**
> Only for your own personal use, or use within your organization only. If you distribute software that incorporates elements of GNU FreeFont, the distribution as a whole must be released under the GPL.

**Comment by SteelWagstaff** [comment]
Consider making these typefaces part of the work being done for https://github.com/pressbooks/pressbooks-malala/issues/5 + https://github.com/pressbooks/pressbooks-malala/issues/6?

**Comment by SteelWagstaff** [comment]
Testing here: https://integrations.pressbooks.network/steelstest/chapter/unicode-test/. Looks good, thanks.
