### ISSUE TITLE
Improve contributor management options

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#205]
### Feature Description

Currently, contributors must be created singly, and there's no way to share contributors between books. 

Two suggestions to improve this: 
1. Allow bulk creation of contributors (possibly through uploading a CSV file)?
2. Allow selections/lists of contributors to be downloaded from one book and uploaded to another book.

### Feature Use Case

Would be particularly helpful in situations where a book has dozens of contributors (in a large collaboratively produced student text, for example), and would be useful in situations where the same group of individuals are contributors to many texts on the same network (common at institutions where instructional staff are filling similar publishing functions for many books).

**Comment by xaurey** [comment]
+1 On this.
It would be relevant to synchronize contributors between books, so you don't have to recreate the same contributor each time.

**Comment by SteelWagstaff** [comment]
Closing in favor of https://github.com/pressbooks/pressbooks/issues/1824
