### ISSUE TITLE
Force export of EPUB without dependencies

### ISSUE THREAD

**Issue by pbstudent** [pressbooks/ideas#214]
### Feature Description
Be able to export to EPUB and check offline.

### Feature Use Case

Creating dependencies for stand alone PB on hosted WP sites is not usually possible. 

### Other Notes
Not sure if dependency is the EPUB generator or/and checker.

**Comment by SteelWagstaff** [comment]
The required dependency is EPUBCheck.

**Comment by pbstudent** [comment]
Perhaps a kind of EPUBCheck plugin would overcome external server dependencies, just as the PDF plugin (in the past) was able to over PDF server dependency?  Otherwise, online LibreOffice could be a promising publishing alternative.

**Comment by SteelWagstaff** [comment]
Won't fix
