### ISSUE TITLE
Harvester Page

### ISSUE THREAD

**Issue by pbstudent** [pressbooks/ideas#216]
### Feature Description
A page option on Home Library Site that aggregates and searches both local and connected open source pressbooks servers.

### Feature Use Case

Ability to search in a book, across a Pressbooks library, or across all Pressbooks libraries. In addition, connectivity options external to Pressbooks for endusers.

### Other Notes
There is always the option to embed a Google scholar search but this tends to be to granular. A harvester such as https://pkp.sfu.ca/ohs/ would enrich the search experience. Display of latest releases would be useful.

**Comment by SteelWagstaff** [comment]
@pbstudent we're currently working on what we envision will be a single Pressbooks directory with references to all books published across all known PB installations. See #208

**Comment by SteelWagstaff** [comment]
Closing as this idea is a duplicate of #208
