### ISSUE TITLE
Editor focus

### ISSUE THREAD

**Issue by pbstudent** [pressbooks/ideas#217]
### Feature Description
Last edit copy/paste from wordprocessor, or saving page results in focus remaining at location in HTML editor of current operations. 

### Feature Use Case

Editing a chapter either by, copy/paste from a wordprocessor, or saving the page, should keep the focus of where the cursor was editing the page rather than sending the focus to the top of the page.

### Other Notes

Current way of editing looses time in loss of focus when saving or copy/paste insertions.

**Comment by SteelWagstaff** [comment]
Won't fix
