### ISSUE TITLE
Built-in Inline Annotation

### ISSUE THREAD

**Issue by pbstudent** [pressbooks/ideas#218]
### Feature Description

Ability for readers or content developers, to annotate (and show/hide) in text.

### Feature Use Case

Two typical cases in an academic context of an open e-textbook:
Case 1. collaborating authors want to comment inline.
Case 2. readers want to comment inline

### Other Notes
Currently you have to use an external system that requires login to provide inline comments. There is no autonomous (i.e., built-in) way to handle annotations for private or public, similar to WP comment facility. However, there may be open source plugins that could be adaptable to Pressbooks, such as http://aroc.github.io/side-comments-demo/  and http://annotatorjs.org/ . In particular, https://github.com/aron/annotator.offline.js linked to private and public views would not be dependent on an external service.

The comments within a book site could be collected, similar to a search page, as per example - https://h2o.law.harvard.edu/  .

Additional reference: https://blog.timowens.io/inline-commenting-with-wordpress/

It is noteworthy that there have been different strategies to presenting comments such as https://wordpress.org/plugins/rollerblade-app/ and https://wordpress.org/plugins/ilannotations/ .

**Comment by SteelWagstaff** [comment]
> Currently you have to use an external system that requires login to provide inline comments. There is no autonomous (i.e., built-in) way to handle annotations for private or public, similar to WP comment facility. However, there may be open source plugins that could be adaptable to Pressbooks, such as http://aroc.github.io/side-comments-demo/ and http://annotatorjs.org/ 

@pbstudent are you suggesting that instead of our currently supported integration with Hypothesis (https://guide.pressbooks.com/chapter/hypothesis-for-webbook-annotation-comments/) that we take on and add native annotation features directly to Pressbooks? If so, you should know that we're _very_ unlikely to do this. Also, I'm not sure if you're aware, but Hypothesis is built on top of annotatorjs.

**Comment by pbstudent** [comment]
External and internal systems each have advantages and disadvantages. A WP plugin that does not require external logins and API is a more centralized approach, just as Pressbooks (PB) does not require external elements to function. The main idea is a localized WP annotation plugin that would be compatible with PB, as the focus of PB continues to be on simple e-book publishing.

Note: WP annotatorjs plugin - https://github.com/openannotation/annotator-wordpress
requires external login to function.

Perhaps more independent wp annotation plugin integration in the future.
