### ISSUE TITLE
BookODF

### ISSUE THREAD

**Issue by pbstudent** [pressbooks/ideas#219]
### Feature Description

Combine ODF into a book format using https://webodf.org/

### Feature Use Case

Ability to pipeline libreoffice document directly to Pressbooks and edit online with commenting; incorporating all the goodness of Pressbooks revisions and accounting, etc.

### Other Notes
example
https://webodf.org/demo/ci/wodotexteditor-0.5.9/localeditor.html

**Comment by SteelWagstaff** [comment]
@pbstudent how is what you're asking for here different from the currently supported 'import' routine for .odt files?

**Comment by pbstudent** [comment]
Very different paradigm to current Pressbook, and others such as BookPress, Anthologize, etc.
The inline ODF editor mimics GoogleDocs and is similar to WordPress inline block editing. WebODF and GoogleDocs are the convergence of Wordprocessing and web, whereas Pressbooks modality is simplified web editing management system. That is, CSS + internal web editor view => external web published view.

From a convenience perspective, LibreOffice editing and CSS are WYSIWYG, with a sidebar for modifying CSS and viewing result in real-time templating.

The current modality of Pressbooks is analogous to WordPerfect reveal codes of the 1980's, which is why MSWord became popular because it provided a convenience in WYSIWYG.

Thus, the future of Pressbooks needs to consider a more convenient approach for endusers to be able to edit in WYSIWYG and easily create templates.

Ideally, a document format that is editable on- and off-line is more useful and flexible. Hence, webodf offers a different way to think about enduser document publishing on the net. Since webodf is a relatively new application compared to Pressbooks, it is somewhat limited by the offline application - e.g. LibreOffice - which has great difficulty in merging several documents into a book. Whereas, Framemaker offline application strength is combining documents into a book.

Pressbooks, BookPress, and other web CMS publishing applications combine documents (i.e., posts/pages) into books, thereby adding a convenience factor, yet to be realized in webodf. However, ease of WYSIWYG and templating in Pressbooks remains challenging, as noted by endusers trying to accomplish APA formatting.

Does that help explain context and ideas?

**Comment by SteelWagstaff** [comment]
Won't fix.
