### ISSUE TITLE
export of single chapters and parts on the fly

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#22]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [X] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To be able to export a chapter or all the chapters of a part. To export on the fly would increase the speed of the proces or revision and would make easy to review a content for a specific day.

### Feature Use Case

If we have students and we have one part for one exam, we can easy to export and to share the specific content.

Some times we have to see how looks like a chapter on a pdf as we have to see if the contet is well adaptated to the size of the papper.

### Other Notes

Now, we have to export the full book, some times 1.000 pages  and the content is not always important for a specific matter. So to be able to have just the pages that matter, would help.

I think is a bad idea to save the exportations in the hard drive, as it would make many files in the server from all the different parts or chapters. As the content would be update all the time, maybe, it would be complicate to know if the pdf is update or not. In long time would be full of files that no longer exist in the web page version. So, on the fly is the best solution. Each time we need one copy, we just made it.

**Comment by greatislander** [comment]
This is already on our [roadmap](https://pressbooks.org/roadmap).
