### ISSUE TITLE
Add a metadata field in Book Info that can link to Adoption Form for book 

### ISSUE THREAD

**Issue by PressbooksLiz** [pressbooks/ideas#226]
### Feature Description

One more metadata field option on the home page 

### Feature Use Case

People would like to know who is using their OER, and who is using the cloned version. For that reason, it would be great if there were a formal place to put a link to the adoption form on the homepage (that would get cloned). Without having to write code to embed some long Google form link

**Comment by SteelWagstaff** [comment]
Closing in favor of #321
