### ISSUE TITLE
Add a caption field for videos, just like the caption field for images

### ISSUE THREAD

**Issue by luis-r-izquierdo** [pressbooks/ideas#233]
### Feature Description

I'd like to be able to insert a caption for uploaded videos (i.e. a description of the video below the player), and have the caption formatted just like the captions for the images.

### Feature Use Case

When I insert a video, the caption is not inserted, even if the video does have a caption in the media library. Once inserted, if I click on the video to edit it, there is no field to insert a caption (in contrast with what happens with the images).

There are workarounds using CSS, but it is hard to make the workarounds behave consistently for all export formats.

**Comment by SteelWagstaff** [comment]
Won't fix -- I'm afraid this isn't a standard feature of the HTML spec for the `<video>` element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video. You could wrap the video in a `<figure>` or `<div>` element instead? Using figcaption might get you what you're looking for?

**Comment by luis-r-izquierdo** [comment]
Thanks a lot Steel. That is what I ended up doing.
I hope you spend a wonderful Christmas with your family.
All the best,
Luis
