### ISSUE TITLE
To save the exports in one folder

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#24]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [X] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To save the exports of the books in just one folder

### Feature Use Case

If the backups of the books are in just one folder, we can decided if we have that folder in the backup or not. So it would be much simple and faster to create the backups if we have slow servers and to save it in the hardrive 

### Other Notes
as each book can be 25 mb, if we have 5 last export of 10 books we have 5 * 10 * 25mb = 1,25 Gb.
It requires too much memory for no reason. As the most of the time, that exports are not important maybe.

**Comment by greatislander** [comment]
We run Pressbooks.com, which has 60,000 books written by tens of thousands of users. It makes sense for each book's exports to be in their own folder — users should not be able to access other users' book exports. We won't be making a fundamental change to the folder structure of Pressbooks like this; the use case is not compelling for a broad range of uses.
