### ISSUE TITLE
Feature Request: Support for multiple editions

### ISSUE THREAD

**Issue by marcusschiesser** [pressbooks/ideas#240]
Books usually have multiple editions.

Wordpress already supports revisions of posts / Pressbooks therefore supports revisions of chapters.

Right now, always the latest revision of a chapter is shown and therefore the latest edition of the book.

The feature request is about to define at any point in time an edition of a book. For this purpose there will be a button: "Create edition" in the book backend. After pushing the button, the admin is asked for a unique name of the edition.

This button internally marks the revision number of each chapter.

If a reader accesses the edition of the book (with a different URL), the chapter in the revision that belongs to the edition is shown.

In the URL the edition-name is used, e.g.

http://{site}/{book-name}/ accesses the latest edition (as it is now)

http://{site}/{book-name}/{edition-name} accesses the edition with the given name

**Comment by SteelWagstaff** [comment]
Related: https://github.com/pressbooks/pressbooks/issues/215

**Comment by colomet** [comment]
in our installation, we do clone the book with a new name to save the book in an old edition. In that way, we always have the original book with the good urls and we  are archiving the old book for historical purposes 

I think, a good aproach is to have a clone buttom for revisions, each time we clone the book, a new id is added automatically to the book name. also, isBaseOn will point the original book from the old versions, with that, we can use rel="canonical and to avoid duplications to google.

**Comment by SteelWagstaff** [comment]
Closing in favor of https://github.com/pressbooks/ideas/issues/296
