### ISSUE TITLE
Pressbooks night mode

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#25]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [X] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

As twitter and the e-readers, we have to be able to have a functionality tha help if we read in the night.

### Feature Use Case

To read from the bed or in a place without light.

### Other Notes

https://twitter.com/twitter/status/757969656493649921

**Comment by colomet** [comment]
![auto-night-mode-ibooks](https://user-images.githubusercontent.com/3929177/37561861-f2253612-2a59-11e8-8812-a2c693553222.jpg)

White - Sepia - Night

**Comment by SteelWagstaff** [comment]
I think it's generally best to leave this to the web browser. See https://www.pcmag.com/feature/369568/how-to-enable-dark-mode-on-your-web-browser/4. Closing issue for now.
