### ISSUE TITLE
"Show in table of contents" option for front matter and back matter in PDF

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/ideas#250]
### Feature Description

Some authors and book creators want to include front matter or back matter posts in their printed books that aren't included in the table of contents. This may include author information, etc, which are sections of a book that a reader would generally expect to find at the beginning or end of a book but wouldn't intentionally look for in the table of contents. 

Ideally, this setting would be available per-post rather than a universal setting controlled by a theme option. The "Show in PDF TOC" setting could exist as a part of the "Status & Visibility" panel (see below). 

![Screen Shot 2019-11-27 at 4 59 20 PM](https://user-images.githubusercontent.com/39064028/69762102-42cfa780-1137-11ea-98d7-c6bb3ca3eac5.png)

Note that the table of contents is necessary for navigation and accessibility in digital formats. This option should only be available for PDF. 

### Feature Use Case

Generally benefits fiction, prose, and print book-focused users.

**Comment by SteelWagstaff** [comment]
Won't fix for now
