### ISSUE TITLE
WP TOOLBAR ENHANCEMENT

### ISSUE THREAD

**Issue by pbstudent** [pressbooks/ideas#258]
### Feature Description

![WP-TOOLBAR](https://user-images.githubusercontent.com/24277755/70218026-88e1c800-1742-11ea-9a8c-769b154d175f.png)

Functions to avoid the usual time to navigate screen to function.
### Feature Use Case

To save, preview without having to scroll. Features, not present in editor toolbar.

### Other Notes
There are plugins to accommodate such a feature but they tend to be either old (i.e., incompatible with current WP version) or contain excess features (e.g. custom colour). In example, [https://wordpress.org/plugins/toolbar-publish-button/] (https://wordpress.org/plugins/toolbar-publish-button/) .

**Comment by SteelWagstaff** [comment]
Won't fix.
