### ISSUE TITLE
Gif as cover page image

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#26]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [X] Book themes
- [ ] Integration with third-party services

### Feature Description

maybe is nice to allow to have Animated Gif as a cover of the book

### Feature Use Case

Some books authors need somehting more special for the covers, so that is an option.

### Other Notes

https://ebookfriendly.com/best-animated-book-covers/

**Comment by SteelWagstaff** [comment]
Won't implement.
