### ISSUE TITLE
To add the post id to the url

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#260]
### Feature Description

![Captura de pantalla 2019-12-17 a las 10 38 23](https://user-images.githubusercontent.com/3929177/70983671-6a23ef80-20b9-11ea-81af-6ba156539595.png)

To have the chapter and part id in the url. 

https://example.com/book1/chapter/127/that-is-a-page/

### Feature Use Case

many times the pages change the name, if so, the link is not longer userful. By having the id of the page, instead of just the name, the link will still work after a change of the post name since the id is always the same.

Also, have backward compatibility, the current ulrs of the pages without the id will work since wordpress recognices the page name, the id or the combination of both.

**Comment by colomet** [comment]
many websites have the title in the url for seo purposes but they work with the id of the page. Like:

shutterstock.com/es/image-vector/augmented-reality-related-line-icon-set-1234124350

works also with 

shutterstock.com/es/image-vector/1234124350

**Comment by colomet** [comment]
also, the performance will increase: https://digwp.com/2011/06/dont-use-postname/

**Comment by SteelWagstaff** [comment]
@colomet We are not planning to change the permalink structure for Pressbooks itself anytime soon, but you could probably do this in your own fork, if it was important to you? You can already load a chapter using its post number. For example `https://integrations.pressbooks.network/opentextbookswithstudents/?p=20` will resolve to the chapter with permalink `https://integrations.pressbooks.network/opentextbookswithstudents/chapter/open-pedagogy/`. Hope that helps somewhat?

**Comment by colomet** [comment]
Thanks for the message

Yes, I do use that one for internal use. 

But I´m worried about if authors change the URL of the page and that breaks the students saved links.
