### ISSUE TITLE
Add 'additional author information' option for chapter-level metadata

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/ideas#267]
### Feature Description

In scientific writing, additional author information is often represented by asterisks. While Pressbooks offers an option to add footnotes, it's current not possible to create un-numbered footnotes. It's also not possible to add footnotes to elements that aren't in the editor, including titles, author, etc. 

A client has requested that a setting be created so that additional author information can be denoted by an asterisk in the bottom of the first page of a chapter. 
![Screen Shot 2020-01-21 at 2 59 41 PM](https://user-images.githubusercontent.com/39064028/72838638-a91c0680-3c5e-11ea-8aa4-bbfbc7567c18.png)

They suggest that an additional field be added to the chapter metadata section where author data could be entered. If the field is empty, no footnote will be inserted. If the field is filled in, the footnote will appear with an asterisk. 

![Screen Shot 2020-01-21 at 3 00 40 PM](https://user-images.githubusercontent.com/39064028/72838700-cb158900-3c5e-11ea-8dc4-dedc6238dacc.png)

### Feature Use Case

Scientific writing, scholarly journals, etc.

**Comment by SteelWagstaff** [comment]
There is currently a 'description' field available in the contributors creation interface. 
![Screenshot from 2020-01-22 09-30-35](https://user-images.githubusercontent.com/13485451/72907707-f9947200-3cf9-11ea-9c9c-a2eb62f220d5.png)

At present we don't display this information anywhere, however. I'd propose either using that existing field or adding a new custom-built field to the taxonomy for this purpose and allowing it to be displayed in this manner.

**Comment by SteelWagstaff** [comment]
Closing in favor of https://github.com/pressbooks/pressbooks/issues/2323
