### ISSUE TITLE
Investigate upcoming SameSite Cookies changes and their impact on embedded content (including in the LMS)

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#272]
See: https://web.dev/samesite-cookies-explained/ + https://blog.chromium.org/2019/10/developers-get-ready-for-new.html + https://courses.uchicago.edu/2020/01/30/canvas-embedded-content-not-displaying/

One user has reported: 
> I first disabled third party cookies in chrome by going to settings > scrolling down and clicking 'advanced' > under the 'Privacy and security settings,' clicking on 'site settings' > then under 'Permissions,' clicking on 'Cookies and site data' > clicking on the "Block third-party cookies" switch. For reference, I'm currently using Chrome Version 79.0.3945.117

> I went into sandbox canvas course, and embedded this chapter: https://wisc.pb.unizin.org/attest/chapter/test-h5p-chapter/ into the course via TCC.

> I logged out of my admin account and logged in in as a test student for that course. When I accessed the assignment here's what I saw: 
![image (2)](https://user-images.githubusercontent.com/13485451/73787010-008e9c00-4760-11ea-9c23-2bcb77520c59.png)

> There is a way for people to manually allow cookies for the site (below), but it's still very likely that students/instructors will get tripped up on this.

> Currently, we're going to request that instructors check the box which launches pressbooks (and other impacted tools) in a new tab, but this also means that folks will be missing out on that 'everything plays well with canvas' feature that folks like so much about using Pressbooks. To be fair, any text or images from Pressbooks should be fine, I haven't tested youtube or kaltura-embeds yet though. We will also be letting folks know they can switch over to firefox if they'd like, but since so many people use Chrome it would be nice if there was another way around this!

**Comment by SteelWagstaff** [comment]
Testing notes from Chrome 80.0.3987.100. Sample course in Canvas that can be used for testing: https://canvas.instructure.com/courses/1741276.
Currently, if third party cookies are not manually disabled, the browser console will display a series of messages that say 
> A cookie associated with a cross-site resource at https://integrations.pressbooks.network/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Here's a screenshot of the cookies set by Pressbooks on https://canvas.instructure.com/courses/1741276/modules/items/28141219 for example:
![Screenshot from 2020-02-18 13-19-22](https://user-images.githubusercontent.com/13485451/74770196-65aebb00-5251-11ea-9b25-47b3c6908a8a.png)

If the user manually disables third party cookies in their browser, then no H5P activities will load. Instead, they see a series of uncaught DOM exceptions in the console. Example: 
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at RequestQueue.H5P.RequestQueue.RequestQueue.clearQueue (https://integrations.pressbooks.network/app/plugins/h5p/h5p-php-library/js/request-queue.js?ver=1.15.0:77:17)
    at new offlineRequestQueue (https://integrations.pressbooks.network/app/plugins/h5p/h5p-php-library/js/request-queue.js?ver=1.15.0:217:18)
    at HTMLDivElement.<anonymous> (https://integrations.pressbooks.network/app/plugins/h5p/h5p-php-library/js/h5p.js?ver=1.15.0:139:31)
    at Function.each (https://integrations.pressbooks.network/app/plugins/h5p/h5p-php-library/js/jquery.js?ver=1.15.0:2:5257)
    at init.each (https://integrations.pressbooks.network/app/plugins/h5p/h5p-php-library/js/jquery.js?ver=1.15.0:2:2013)
    at Object.H5P.init (https://integrations.pressbooks.network/app/plugins/h5p/h5p-php-library/js/h5p.js?ver=1.15.0:93:60)
    at HTMLDocument.<anonymous> (https://integrations.pressbooks.network/app/plugins/h5p/h5p-php-library/js/h5p.js?ver=1.15.0:2821:11)
    at c (https://integrations.pressbooks.network/app/plugins/h5p/h5p-php-library/js/jquery.js?ver=1.15.0:2:7857)
    at Object.fireWith [as resolveWith] (https://integrations.pressbooks.network/app/plugins/h5p/h5p-php-library/js/jquery.js?ver=1.15.0:2:8658)
    at Function.ready (https://integrations.pressbooks.network/app/plugins/h5p/h5p-php-library/js/jquery.js?ver=1.15.0:2:3266)
```
The cookies list list now looks like 
![Screenshot from 2020-02-18 13-26-53](https://user-images.githubusercontent.com/13485451/74770688-5714d380-5252-11ea-8937-c363262367dc.png)

**Comment by SteelWagstaff** [comment]
The same user who reported the issue initially writes: 
> Chrome will be blocking third-party cookies by default. It's related to the SameSite issue detailed in this chromium blog post: https://blog.chromium.org/2020/02/samesite-cookie-changes-in-february.html. Because the population of Chrome users who will have this setting set by default will be expanding throughout February, not all users will necessarily experience this issue in v80 of chrome, however when the updates are completely rolled out, it seems very likely that all v80 (and later) chrome users will be impacted. 

Here's a screenshot of the errors thrown when that user attempts to open Pressbooks chapter embedded in Canvas via TCC in Chrome Canary (v82.0.4056.0) in their campus instance of Canvas.

![image (3)](https://user-images.githubusercontent.com/13485451/74778218-bda0ee00-5260-11ea-978e-eecd714c8955.png)

The console error for this user very similar to the one I pasted above with subtle differences: 
> A cookie associated with a cross-site resource at https://wisc.pb.unizin.org/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032."

The user reports that workarounds include: 
1. having assignments/module items configured to open PB LTI links in new tabs 
1. instructing folks to disable the automatic blocking of 3rd party cookies. 

> So far we've just recommended that folks use the 'open LTI tool in new window' settings to bypass the issue, but if there was a way to have embeds directly in canvas again, that would be great!

**Comment by SteelWagstaff** [comment]
**Summary:** we should consider implementing a solution which explicitly declares `SameSite=None; Secure` to any required cookies set by Pressbooks. 

See also https://github.com/GoogleChromeLabs/samesite-examples and https://github.com/GoogleChromeLabs/samesite-examples/blob/master/php.md for sample implementations, and several testing/debugging tips here: https://www.chromium.org/updates/same-site/test-debug

**Comment by cagp-dev-mtl** [comment]
After researching, there is an open PR on the HP5 library that solves the issue of blocked localStorage, this PR might also address the Chrome 82 sameSite cookie problem reported by Canvas users.

Open PR:
https://github.com/h5p/h5p-php-library/pull/66
