### ISSUE TITLE
Add open embeddable assessments URLs to auto oembed whitelist

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#285]
We whitelist some oembed providers: https://github.com/pressbooks/pressbooks/blob/9aaea5e1c7ececf2e44bd3968e8e3fc05e13b642/inc/interactive/class-content.php#L344-L353. We should add support for open embeddable assessments in a way that's compatible with existing assessments created by Lumen Learning: https://github.com/lumenlearning/candela-utility/blob/7f7cb0f6077d0b83277e63a54bc3faa7dc28f9ef/includes/cu-oembed.php#L29-L51

**Comment by SteelWagstaff** [comment]
@mcgratay For testing we should determine what happens when links from the following sites are pasted into or occur in texts:
1. https://openassessments.com
2. https://assessments.lumenlearning.com

Expected: oEmbed Behavior should be the same as for other items on our whitelist (openassessments.org, phet, etc.) in webbook and export formats. Example of the latter available in https://integrations.pressbooks.network/candelatestclone2/chapter/what-is-government/ and other books cloned from Lumen Learning networks.

**Comment by mcgratay** [comment]
Tested the Lumen Learning instance of Open Assessments. Links to assessments auto embed now, and all assessments included in cloned books clone successfully. 

There is one minor difference in display of the graceful fallback in export formats: 

![Screen Shot 2020-03-31 at 11 10 30 AM](https://user-images.githubusercontent.com/39064028/78049093-3d31da80-7340-11ea-9cc7-f9c025b14c4f.png)

.org activities are identified explicitly as Open Assessments whereas the Lumen Learning version of Open Assessments are more abstractly called interactive elements. 

https://openassessments.com/ states that the site has yet to be launched, so I was unable to find any activities to test.
