### ISSUE TITLE
Warmings just to Super-admin

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#286]
### Feature Description

Site administrators and other roles do not require to see code warmings.

![Captura de pantalla 2020-03-18 a las 17 34 56](https://user-images.githubusercontent.com/3929177/76984332-f9ea6b80-693e-11ea-8c8e-210d2b962c91.png)

### Feature Use Case

Site administrators can be confuse with those warmings and non available options. More fine tuning of options are required. But we can just disable/hide all the non available options and/or warmings to site administrators. Just Multisite administrators will see all those options or warmings

**Comment by SteelWagstaff** [comment]
Here's where dependency errors are produced: https://github.com/pressbooks/pressbooks/blob/0e9057b90033bedd636be877a7afab84cf9162e9/inc/modules/export/namespace.php#L83-L100.

**Comment by SteelWagstaff** [comment]
Won't fix.
