### ISSUE TITLE
Versioning/version control of books

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#29]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [X] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

For diffent cases we need to have the version of the book. We need an automated process for the versioning.

Maybe we can have 2 types of versions. PreRelease version for the control of versions before the Publication Date and the release versions,

I think we can have a version of a.b.c.d. numbers. Where:

- A is incremented when adding, changing or removing PARTS.
- B is incremented when adding, changing or removing CHAPTERS.
- C is incremented when adding, changing or removing METADATA or LINKS while remaining compatible with previous versions,
- D is incremented when a TYPO is fixed (so the update have to have the modification of just one or two words or characters)

### Feature Use Case

We can compare the versions of the book after the cloning.

### Other Notes
I do not know about the change of place of a chapter, if that is an A or B change of the version.

**Comment by colomet** [comment]
is the first step to keep the control of the clone books and the future comparation of copies.

https://discourse.pressbooks.org/t/version-control-to-between-copies-of-books-and-across-networks/106

**Comment by SteelWagstaff** [comment]
Closing in favor of #296
