### ISSUE TITLE
admin menu sync with multisite cappabilities

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#291]
### Feature Description

To integrate the admin menu with the required cappabilities.

### Feature Use Case

If i change the cappabilities to a role, giving to a new role all the multisite cappabilities, the new role allow to the users to see all the multisite settings but the top menu have no direct acces to the multisite section.

Now, if we need to have a new role, we have the permisions but not an easy way to use those permisions.

Admin top menu with multisite direct link
![Captura de pantalla 2020-03-27 a las 19 53 50](https://user-images.githubusercontent.com/3929177/77790301-e046d380-7064-11ea-9a50-18dc60c0036c.png)

New role with multisite cappabilities, as you can see, he have not the direct Network Admin acces.
![Captura de pantalla 2020-03-27 a las 19 54 01](https://user-images.githubusercontent.com/3929177/77790303-e2109700-7064-11ea-8a06-858fc1927311.png)

**Comment by SteelWagstaff** [comment]
@colomet I'm not sure I understand what you're trying to do here. It sounds like you've created a new custom role for users and are not sure how to give that user role the permissions needed to see the 'Network Admin' menu. Is that correct? If so, this isn't something that we'd likely add to core Pressbooks. You or your developers could probably handle this yourselves by modifying this, however: https://github.com/pressbooks/pressbooks/blob/0e9057b90033bedd636be877a7afab84cf9162e9/inc/admin/laf/namespace.php#L716-L769.
