### ISSUE TITLE
clone a book sync with create_sites cappability

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#292]
### Feature Description

to be able to clone books to non-administrators if create books at setting page is not activate by synchronising create_sites capability with clone books option.

### Feature Use Case

If we need a new role where they can clone books, now is not possible, since create_sites capability is not connected with clone books. So, or just super administrators can manage sites or all the users can create sites, but some times, we need somebody who takes care of the community but without a possibility to touch users sites.

Anyway, by having an efficient distribution of the capabilities, we have the possibility to have the roles we required at any time

Also, to load the admin page requires too much time if all the options are available, to be able to choose which options load in each role, increase the performance time of the page.

**Comment by SteelWagstaff** [comment]
Won't fix
