### ISSUE TITLE
Allow network managers to bulk change book info

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#293]
### Feature Description

To be able to change book info fields at once for all the books or selected books

### Feature Use Case

Some times language, license or any other field requires an update. Now, we have to open one by one all the fields, in a situation where we have 300 books or more, the situation is slow. But by having one centralised place, will make possible the updates in no time.

The options will be, at Site 1 (Aldine) to have a custom post book_info, the same as with the books and a new metabox with all the books where we can choose which books to sync (like in the image)

![Captura de pantalla 2020-03-28 a las 11 02 21](https://user-images.githubusercontent.com/3929177/77820602-c9939180-70e3-11ea-8084-eb2d1fe6da03.png)

### Other Notes

We do use in one plugin a similar system, so we can choose which option is available in new books by default or not (like a placemark), even if the site admins can change or not.

**Comment by colomet** [comment]
Related to: pressbooks/ideas#282 pressbooks/pressbooks-network-analytics#381 pressbooks/ideas#280

**Comment by colomet** [comment]
In situations where the site (a publishing house) is the responsibility of all the books, that is an important and useful requirement. So, the chief editor can manage as required.

**Comment by SteelWagstaff** [comment]
Closing in favor of https://github.com/pressbooks/pressbooks-network-analytics/issues/64
