### ISSUE TITLE
Smart redirection http - https

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#294]
### Feature Description

Open pages with the required URL: if the domain has a secure connection, with secure connection https if not, then, not.

### Feature Use Case

Some times, we follow a new page but the URL of the page may or may have not the secure connection. That is a problem in secure connexions since the browser does not recognise the open session.

### Other Notes
https://pressbooks.community/t/problems-with-acces/1289

**Comment by SteelWagstaff** [comment]
Closing as this is a server configuration issue, rather than a Pressbooks code issue. See https://pressbooks.community/t/problems-with-acces/1289/2?u=steelwagstaff for a suggestion.
