### ISSUE TITLE
Front Matter type with dinamic content

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#295]
### Feature Description

To be able to have templates in Front Matter where atomaticaly the conten are created.

### Feature Use Case

The h5p list of activities (Instead of /h5p-listing/) or the list of books of the author can be shown by just activating in a page the new required template. 

### Other Notes

![Captura de pantalla 2020-04-02 a las 9 29 41](https://user-images.githubusercontent.com/3929177/78221992-b0fcf000-74c4-11ea-9f46-ba855af6de1c.png)

**Comment by SteelWagstaff** [comment]
Won't fix
