### ISSUE TITLE
Last page of the book a redirection to the continuation book

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#3]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [X] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

Some times the books have a continuation. So, maybe we can have in the end of the book a page with just a link to the continuation of the book.

### Feature Use Case

Students that have different books for one lesson. Grammar 1, 2 and 3. Spanish level 1 and 2 ... or continuation book like The Lord of the rings I, II and III.

Once the first book is finish, they can keep reading the second book and they do not have to lose time searching the book.

### Other Notes
Each time I have to review a collection of books,  after finish a book I have to search for the next book from the same collection.

**Comment by SteelWagstaff** [comment]
@colomet I'm going to close this old ticket. You can already do this by adding a link in the final chapter or back matter.
