### ISSUE TITLE
Analytics information for non login users

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#30]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [X] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To know with a counter how many people read a page.
To track by cookies the pages a user read, so he would know if he already read a page or not
To track if the page is full read or just opened.
To know how many times a user read a page.

### Feature Use Case

They know if they read the page, if other people is reading the page, what is missing to read ... information

### Other Notes

We can change the color of the TOC each time a user read a page maybe or to have an icon somewhere where we can know how many times we  or people read the page and with a different color if we did read the page in the past.

https://discourse.pressbooks.org/t/simple-post-views-counter/60

**Comment by SteelWagstaff** [comment]
We won't be adding this kind of behavioral tracking to core Pressbooks any time soon. Some of what you're looking for can be done with something like Google Analytics and other parts of it could be accomplished with CSS targeting the `:visited` pseudo-class selector: https://css-tricks.com/almanac/selectors/v/visited/
