### ISSUE TITLE
theme refresh

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#301]
### Feature Description

To be able to refresh all the CSS themes and maybe permalinks too. 

(switch_all_multisite_themes(); )

### Feature Use Case

If we do modify the CSS of a theme, we have to change one by one all the themes, in a situation where we have many many themes, it requires a lot of work. Since we can **Lock your theme at its current version**. That will not destroy if any book administrator has a specifical situation.

Maybe it can be also good if at once we refresh the permalinks, so we can avoid some type of situations where it may be required.

### Other Notes

https://guide.pressbooks.com/chapter/customizing-your-exports-with-custom-styles/#implicationsforpressbookscustomcss

**Comment by SteelWagstaff** [comment]
Won't fix.
