### ISSUE TITLE
googleweblight integration

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#307]
### Feature Description

To work with googleweblight.

### Feature Use Case

Google shows faster, lighter pages to people searching on slow mobile clients. So far, the cover page do not works (so, the population in countries or regions with bad internet conexion or just 2G have a bad experience).

Since Open education is most important for those areas, I think I will be a good idea to integrate it.

The main problems are:

- the table of contents
- the cover page (table of contents, book info and metadata).

Maybe we can have a static version of those pages or sections without javascript.

### Other Notes

https://googleweblight.com/i?u=https://open.books4languages.com/english-b2-grammar/&hl=
http://andreas-wpv.blogspot.com/2015/09/web-light.html
https://support.google.com/webmasters/answer/6211428?hl=en

**Comment by SteelWagstaff** [comment]
Won't fix
