### ISSUE TITLE
Custom header and e-mail sender in emails

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#308]
### Feature Description

To be able to use custom information in the emails information

### Feature Use Case

Users do not know what pressbooks is, by receiving an email from Pressbooks they may think  is spam or a fake account. But if we can choose the main domanin name instead, they will open the email without questioning.

### Other Notes

![Captura de pantalla 2020-04-30 a las 13 53 56](https://user-images.githubusercontent.com/3929177/80707461-47372c80-8aea-11ea-8465-c669bb9fbdbb.png)

**Comment by SteelWagstaff** [comment]
@colomet Closing, as you can control this yourself without altering the Pressbooks core code (we didn't set the send from email address you're showing in this screenshot, for example). Many open source users do this with an SMTP plugin of some kind. See https://pressbooks.community/t/no-emails-coming-in/531/5 for some ideas.
