### ISSUE TITLE
Analytics information for login users

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#31]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [x] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To know the pages a user read. 
The number of times the user read a page. 
The minutes the user spend with a page.
If the user open the links.

### Feature Use Case

Teachers need to know if the students of the teacher did use the content and how they did use.

### Other Notes
We need a information panel for the students (an open one maybe).

**Comment by colomet** [comment]
https://www.oreilly.com/ideas/education-data-analytics-learning

**Comment by SteelWagstaff** [comment]
Won't implement
