### ISSUE TITLE
lang attribute to identify chunks of text

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#315]
### Feature Description

To be able to use the `lang` attribute to identify chunks of text in a language that is different from the document’s primary language.

### Feature Use Case

Language books with two languages in a page.

### Other Notes

https://developer.paciellogroup.com/blog/2016/06/using-the-html-lang-attribute/

**Comment by SteelWagstaff** [comment]
Can't do this easily with current tinyMCE editor inherited from WordPress, unfortunately. Work around is to manually add tags in HTML editor.
