### ISSUE TITLE
Titles with anchors

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#32]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [X] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

Soon gutenber will change all, but we need to have titles with anchors, so is easy to copy a title and to share the link (like github)

### Feature Use Case

Teachers can share the link of one specific title or subtitle.

### Other Notes

https://discourse.pressbooks.org/t/titles-with-anchor/64

**Comment by SteelWagstaff** [comment]
Closed in favor of https://github.com/pressbooks/ideas/issues/174 (which duplicates this request)
