### ISSUE TITLE
Book Usage Analytics (downloads/adoptions)

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/ideas#320]
### Feature Description

Have a native analytics dashboard (for each book, and for the network) that tracks reader / usage activity, including: 
1. book downloads
2. download formats
3. book visits
4. page visits
6. adoptions (self reported prompt?)  
7. number of other institutions that have cloned this book 
8. other things? 

Bonus if we can track this across all cloned versions of a book, and report the data on the Directory. 
 
### Feature Use Case

For authors: 
-- it is very gratifying for OER and other creators to see how their books are being used. This should be information creators have easy access to.

For Higher Ed administrators: 
-- Seeing reach/spread of a book helps administrators/funders define the return on investment on publishing projects, and helps institutions see the value (prestige/visibility, student savings etc) of each project and Pressbooks in general.   

### Other Notes

While we enable Google Analytics (which for Networks is only visible to the network manager), this really could/should be a native feature of Pressbooks. There are existing stats packages (such as matomo.org) that we could consider.

**Comment by SteelWagstaff** [comment]
Good ideas, Hugh. We've thought about a closer integration with Fathom: https://usefathom.com/ in the past & want to revisit this soon (see convos in internal Slack & past product meeting agendas).

**Comment by SteelWagstaff** [comment]
We'll be adding Koko Analytics to our hosted networks in the near future, which will provide a dashboard with basic page view information: https://www.kokoanalytics.com/wp/wp-admin/index.php?page=koko-analytics#/. Open source users may also want to consider using it or a similar solution if they're interested in this functionality.
