### ISSUE TITLE
Replace references to 'whitelist' and 'blacklist' 

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#323]
Replace all user-facing references to 'whitelist' and 'blacklist' with 'allowlist' and 'blocklist' in code and documentation.

See https://github.com/search?l=PHP&q=org%3Apressbooks+whitelist&type=Code + https://github.com/search?l=PHP&q=org%3Apressbooks+whitelist&type=Code

Look for HTML, Blade, Markdown occurrences.
 
Steel will work on guides/KB docs with Amy.

**Comment by pb-amy** [comment]
### Support

**Network manager:**
- [x] https://guide.pressbooks.com/chapter/embedded-media-interactive-content/
- [x] https://guide.pressbooks.com/chapter/users/

**User:**
- [x] https://networkmanagerguide.pressbooks.com/chapter/network-iframe-whitelist/
- [x] https://networkmanagerguide.pressbooks.com/chapter/debug-file-validation/
- [x] https://networkmanagerguide.pressbooks.com/chapter/network-options/

**Misc:**
- [x] https://pressbooks.com/2018/11/28/whats-new-on-pressbooksedu-glossary-creation-doi-integration-and-more/
- [x] https://pressbooks.com/2019/04/05/whats-in-the-garden-for-q1/

Luckily, there are no guide chapters or macros (canned replies) using this terminology. I will change these terms after this task has been changed in code!

**Comment by richard015ar** [comment]
PRs for front end changes:
- https://github.com/pressbooks/pressbooks-lti-provider/pull/113
- https://github.com/pressbooks/pressbooks-network-analytics/pull/102
- https://github.com/pressbooks/pressbooks/pull/2052

**Blacklist** was not found in any front end / template.

**Comment by SteelWagstaff** [comment]
@pb-amy All guide chapters have been updated with improved language. I think we can probably leave the old blog posts, but will defer to your judgment there.

**Comment by SteelWagstaff** [comment]
Whitelist has been replaced with Allowlist in the user interface in Pressbooks, the Network Analytics plugin, and the LTI provider plugin on integrations and textopress. Ready for release!
