### ISSUE TITLE
Make an option (on by default) to make contributors public/visible & pretty

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/ideas#326]
### Feature Description

Revamp/improve how we handle Contributors, to: 
a) allow better/more complete data input
b) display contributors on the Book Info page
c) build a nice-looking contributor page by default   

Among desired improvements: 
1. Have an option: "show contributors on book info page" (probably on by default)
2. create an auto contributors page at the back of the book, and format it nicely by default
3. for the data input:
a) Make the Description a rich text editor
b) add fields for: URL, Twitter, (other social media), ORCID ID, institution, other things? 
c) enable upload of an author image/headshot

### Feature Use Case

An important driver for contributing to OER and publishing on Pressbooks is public/social recognition for contributions. Currently Pressbooks handles this badly/not really at all. This should be addressed to help Pressbooks better reflect peoples' contributions to OER.
 
Among other things : contributors are not listed by default on the Book Info page, unless hacked into the description. Users wishing to have a contributor page create their own, and often they look crap. 

Further, if done right, this could be valuable data to surface in the Directory (though note that we would likely have to rethink how we assess the unique identity of a user (ORCID would be a great way to do that -- ie if you have an ORCID listed in a Contributor page, we can find you, otherwise not).

**Comment by xaurey** [comment]
+1 
One of the main issue I have with Pressbooks is the impossibility for each author to have his "page" on the network, automatically filled with elements provided in his description, and with a link to the books he/she participated to.
The current way to deal with authors doesn't feel very useful for a good use of this element.
We should be able to add authors/editors/contributors across the network and then link them to one or more books.

**Comment by SteelWagstaff** [comment]
Related to #134

**Comment by SteelWagstaff** [comment]
Contributors are included in core Pressbooks now with their own custom display.
