### ISSUE TITLE
Allow page width to be set on the page level (not just book level)

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#33]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [X] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

Soon gutenber will change the wa we create the content but:

We need to have some types of pages for different purposes. Now we have 3 type of pages(Webbook Width: Narrow - Standard - Wide). But we can just use one for all the chapters. 

Wy not to  be able to choose a different one for each page if are available?

But the real problem is we need a big one for specifical purposes ( a landing template). Some times we need to create a table, a big one and we can not do it in the current way.

### Feature Use Case

Authors could need to create a big table, so the current size of the template do not allow to do it without a scrool of the table. so looks ugly and hard to read the table.

### Other Notes

https://discourse.pressbooks.org/t/could-we-create-a-template-for-posts/70

**Comment by SteelWagstaff** [comment]
Won't implement
