### ISSUE TITLE
Feature for Importing LaTeX Equations

### ISSUE THREAD

**Issue by kartikmann24** [pressbooks/ideas#336]
### Feature Description

Can we create a feature that would automatically import LaTeX equation from various formats?

### Feature Use Case

This feature would automate and import equations a lot easier and faster for books that are equation heavy.

### Other Notes

-

**Comment by SteelWagstaff** [comment]
@kartikmann24 we have an open issue that we hope to work on soon that should address this: https://github.com/pressbooks/pb-mathjax/issues/18
