### ISSUE TITLE
Read full page buttom 

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#34]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [X] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To have a full read page buttom that will show just some of the content before the user fully open the page with the buttom.

![9baa8c60cafe9c12e1087ef91e2b86ee16de61af_1_300x500](https://user-images.githubusercontent.com/3929177/37554406-33bbf26e-29d8-11e8-892a-1d32467be3f3.png)

Quarz or other important newspapers offer such functionality.

### Feature Use Case

Opening the page from a mobile will speed the opening of the page and It will download much less data. Important for the non developed countries.

### Other Notes

https://discourse.pressbooks.org/t/read-full-page-buttom/89

**Comment by colomet** [comment]
Or maybe if the user open the site with a mobile view, if the site have a long scroll, the images are not download till the users do scroll. Like the media queries, just we donwload images if the image is in the next 1000px otherwise, it will not download till the user do scrool and the image is 1000px or less

**Comment by SteelWagstaff** [comment]
Won't implement.
