### ISSUE TITLE
Overhaul & improve contributors feature

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#359]
### Feature Description
Currently, users can enter very limited information about contributors:
![Screenshot from 2021-01-29 14-21-47](https://user-images.githubusercontent.com/13485451/106334357-5137b880-623f-11eb-858b-63bb9025c0da.png)

We should allow people to associate and display more identifiying information about contributors. It may also make sense to allow people to associate similar information with their user profile and more tightly connect the user meta from a user profile with the contributor values. Desired info: website, Twitter, LinkedIn, Orcid, brief textual bio. Info provided should be displayed nicely in various places in the book.

**Comment by NMSalmon** [comment]
I'd love to plus one this request! I'm working with a team at UW who would really appreciate the ability to display what's in the "description" field, and I love the idea of having links to Orcid etc. 

As more folks get involved with cross-institution open pedagogy projects or cross-department resource-sharing efforts, this feature will be more and more relevant.

**Comment by SteelWagstaff** [comment]
Thanks @NMSalmon! I'm working this month on turning this into an epic that we can start tackling soon (possibly as soon as Q2 of this year). See https://github.com/pressbooks/pressbooks/issues/2096 for broad strokes of current thinking (more to come soon).

**Comment by SteelWagstaff** [comment]
Closing in favor of https://github.com/pressbooks/pressbooks/issues/2096 + https://github.com/pressbooks/pressbooks/issues/2323
