### ISSUE TITLE
To delete non used exported files

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#37]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [X] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

Each time we export a file (pdf, epub, xml), the sistem saves the last 5 exports. Some times one export is one file, some times are some files.

Maybe after one month or a time the super admin think is the best for the situation of the network, the system could delete the older exports and to save just one of each format.

### Feature Use Case

In that way we could save space in the hard drive, because we use to forget to delete such files and in my situation, I have books with images and each export takes more than 20 mb. We need to have the last one available, but the olders I don´t believe.

### Other Notes

https://discourse.pressbooks.org/t/exported-files-new-options/91

To control the export proces as super admin #23

**Comment by colomet** [comment]
Files of the export

https://discourse.pressbooks.org/t/files-of-the-export/157

**Comment by colomet** [comment]
Example of a situation where one export is split in 3 

![captura de pantalla 2018-05-28 13 35 35](https://user-images.githubusercontent.com/3929177/40612785-3005160a-627c-11e8-9025-64b93181b17d.png)

**Comment by SteelWagstaff** [comment]
@colomet This issue will be addressed in the forthcoming Pressbooks 5.7 release. See https://github.com/pressbooks/pressbooks/issues/1525 for some implementation details.
