### ISSUE TITLE
 Sprint April 26 - May 7

### ISSUE THREAD

**Issue by iku1deep** [pressbooks/ideas#374]
I can't see the contents

**Comment by SteelWagstaff** [comment]
HI @iku1deep sorry about that. Nearly all of the issues we were working on in this sprint are in private repositories, which mean that they'll be invisible to people outside of the Pressbooks organization for now. The sprint goal was to "Get v2 of Pressbooks Directory ready for launch, start Business Intelligence dashboard research, & work on bug fixes for Pressbooks." We do host monthly product update meetings from 2-3pm Eastern Time on the last Thursday of each month and share [these recordings on YouTube](https://youtube.com/playlist?list=PLMFmJu3NJhet17A4FC_84OVDS8N18YyIo). These meetings include general product updates and demonstrations of new features and designs being planned for Pressbooks products, as well as time for members of the open source community to share news & updates about any general interest Pressbooks-related projects they’ve been working on. Upcoming meeting agendas and any changes to the schedule are generally announced on our open source blog: https://pressbooks.org/blog/. Hope that helps?
