### ISSUE TITLE
Add a filter to Directory  to sort by course level, or at least by institution type  

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/ideas#378]
### Feature Description

Mechanism to filter directory results by course level (or at the least by institution type, ie to show content from Community Colleges).

### Feature Use Case

Different institutions want different kinds of content for different levels of course. Particularly there is a difference among: 
- community college courses
- 4 year university courses
- graduate level courses

Currently there is no way to filter for course level, or even by institution type.

In particular, it could be powerful to filter content from Community Colleges -- as that's a particular 

### Other Notes

Without capturing every book, we could easily add "institution type: community college  OR 4 year," metadata to the network (which we could manage/fill in) that would enable us to add that filter to the Directory, which for instance makes it much easier to find content appropriate for Community College. 

But for each book we could also add a course level metadata field (harder to get the good data though)

**Comment by SteelWagstaff** [comment]
Won't fix
