### ISSUE TITLE
Add LaTeX button to visual editor

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#383]
### Feature Description

As a Pressbooks user, I'd like a quick and simple way to add LaTeX to my book using the visual editor. Ideally, I should be able to click a button or use a keyboard shortcut to open up a dialogue box where I can directly enter my LaTeX code. When I click ok, the code should be wrapped in [latex] shortcodes. If a text selection is highlighted at the time that I click the visual icon, the highlighted text should be wrapped in latex shortcodes. In order words, the button should function much like the custom footnote button in the current visual editor: https://github.com/pressbooks/pressbooks/blob/dev/assets/src/scripts/footnote.js.

### Feature Use Case

Authors who are trying to create a lot of math in their books currently have to add the [latex] [/latex] shortcodes for every single equation. This can become tedious and sometimes leads to errors.

**Comment by gavinpressbooks** [comment]
Tested on Integrations on https://integrations.pressbooks.network/validationtest/wp-admin/post.php?post=5&action=edit

Works as expected. Clicking the LaTeX button in the visual editor while highlighting text wraps the text in the appropriate shortcodes. Having nothing selected and clicking the LaTeX button in the visual editor prompts the user to enter content which is subsequently wrapped in the appropriate shortcodes.
