### ISSUE TITLE
Can sign in button be hidden

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#39]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [X] Book themes
- [ ] Integration with third-party services

### Feature Description

To hidde the sign in buttom if the administrator or superadministrator whant or to change the place (maybe in the footer). Or a message in the login page if the site is close for just registered users.

### Feature Use Case

We use the books from the author point of view, what about the readers? some times they can believe they have to login but they have not. 

Some installations of PB is about authors, some is about readers. So we have to offer a solution for both situations or a solution that help both situations.

### Other Notes

https://discourse.pressbooks.org/t/can-sign-in-button-be-hidden/105

**Comment by colomet** [comment]
In the other hand (old content from Discourse forum)

My people use to have always the same problem. They do not use to find the login of the site the first days as is just in the home page. Is not possible to have it in any page?.
In the footer in order to not use space in the header maybe - maybe in the sidebar menu.

Anyway, I think a place where more information can be find it (the metadata about the page) as the login buttom maybe could be nice


https://discourse.pressbooks.org/t/login-in-chapter-page/226

**Comment by SteelWagstaff** [comment]
Closing as we have no plans to hide the login button in Pressbooks core. Open Source users could hide or move this link through theme. The current 'Sign In' link in the top menu is controlled in the Aldine theme here: https://github.com/pressbooks/pressbooks-aldine/blob/a22ff75e833d0c43eb2771994d188658eb80d712/inc/helpers/namespace.php#L183-L188
