### ISSUE TITLE
'Powered by Pressbooks' footer should include a link to the directory

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/ideas#399]
### Feature Description

We should have a link to the Directory in the footer, beneath the ‘Powered by Pressbooks’ link

![image](https://user-images.githubusercontent.com/61845107/142434357-37d640e3-a946-4b2d-ba8f-ff29d0aaa30f.png)

### Feature Use Case

This would provide navigation to the directory without affecting UX or Call-to-action mechanisms that needs to be researched before implementation.

Desired footer:
Guides & Tutorials | Directory | Contact

**Comment by SteelWagstaff** [comment]
Code goes https://github.com/pressbooks/pressbooks-aldine/blob/8d4725f5fcd2112d14dc94a8401ba8fa22a81f51/footer.php#L107 and https://github.com/pressbooks/pressbooks-book/blob/367a356006b480187f9a47fc6b99fc68832b4a89/footer.php#L66

**Comment by SteelWagstaff** [comment]
Appears as expected on integrations.
