### ISSUE TITLE
"Terms of Service" button on log-in page next to "Register" and "Lost your Password" buttons

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/ideas#403]
### Feature Description

The only way for new users to be confronted by a "Terms of Service" page is when users manually register through the default Pressbooks login method. However, some institutions (namely UTRGV in this case, in December 2021) have suggested that they'd like to make a Terms of Service visible on the log-in page to make it visible regardless of how the user is registering.

<img width="451" alt="Screen Shot 2021-12-02 at 11 41 17 AM" src="https://user-images.githubusercontent.com/61845107/144464994-faf1f384-bd84-4b2a-a410-a062f1c71a2a.png">

### Feature Use Case

While there is the option for institutions to post their Terms of Service to their Header and/or Footer menu, this button on the Log-in page would make it so that it's visible directly at the time of Registration or Log-in.

**Comment by SteelWagstaff** [comment]
Closing in favor of https://github.com/pressbooks/private/issues/1530
