### ISSUE TITLE
Feature: Distinct URL for "Create a Book"

### ISSUE THREAD

**Issue by paradisojr** [pressbooks/ideas#415]
### Feature Description

I'd like to be able to send users to a unique 'create a book' URL that would either allow them to create a book (if signed in) or prompt them to sign in from that page and be kept there (if not logged in). 

### Feature Use Case

Problem: Currently, /wp-signup.php is used for 'sign up' and 'create a book.' Does the system require they use the same URL?

Motive: Since transitioning to SSO, I'm no longer requesting new users sign up and create a book through the above URL.

Desired result: I'd like to be able to launch users directly to the 'create a book' page to streamline the book creation process (1 click), rather than have them login, go the Admin dashboard, and click a button to access the 'create a book' page (3 clicks).

**Comment by SteelWagstaff** [comment]
Closing in favor of https://github.com/pressbooks/pressbooks/issues/2856
