### ISSUE TITLE
To personalize the content with fonts and colors

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#42]
### Feature Scope

- [ ] Accessibility and inclusivity
- [X] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

Can be nice to have a way to select a different font for each h1, h2, h3, h4 h5, h6 and p
Allowing users to find the font they wish for each one of the h and p.

Also to have different colors for different places.

### Feature Use Case

Each book can easily be personalise

### Other Notes

https://discourse.pressbooks.org/t/different-font-for-each-h-and-p/98

# COLOR
![captura de pantalla 2018-03-17 a las 12 24 16](https://user-images.githubusercontent.com/3929177/37554802-253f1076-29de-11e8-8c88-17e2708af67a.png)

![captura de pantalla 2018-03-17 a las 12 23 43](https://user-images.githubusercontent.com/3929177/37554806-2f350cc0-29de-11e8-8b08-d8d04b82d4d6.png)

![captura de pantalla 2018-03-17 a las 12 23 49](https://user-images.githubusercontent.com/3929177/37554807-2f538f42-29de-11e8-95df-69dd3a9eb663.png)

![captura de pantalla 2018-03-17 a las 12 23 55](https://user-images.githubusercontent.com/3929177/37554808-2f7242f2-29de-11e8-8014-d68409781577.png)

# FONT
![captura de pantalla 2018-03-17 a las 12 24 06](https://user-images.githubusercontent.com/3929177/37554810-3583d566-29de-11e8-9e18-f1150d76d6ac.png)

![captura de pantalla 2018-03-17 a las 12 24 10](https://user-images.githubusercontent.com/3929177/37554809-35642a90-29de-11e8-92a2-7a814da5c8ac.png)

**Comment by SteelWagstaff** [comment]
@colomet you may be interested in https://pressbooks.com/2019/10/02/introducing-malala/ and https://pressbooks.org/blog/2019/09/24/font-selector-theme-option/

**Comment by SteelWagstaff** [comment]
Won't implement. Could be considered when theming is next overhauled at Pressbooks?
