### ISSUE TITLE
Move the 'edit' button above the content for logged in users

### ISSUE THREAD

**Issue by cogdog** [pressbooks/ideas#420]
### Feature Description

This is very minor...

It get tedious to always have to scroll to the very bottom of a Pressbooks page to access the Edit button. Why not have one in the Admin bar menu (as Wordpress does) to at least make it close if nearer  the top of the page? Or even a floating one?

### Feature Use Case

It helps anyone who is reviewing content and needs to make a change. I can't speak for others but I often work from the public view.

### Other Notes

I like Pressbooks ;-)

**Comment by SteelWagstaff** [comment]
@cogdog Seems like a simple enough request. Sorry it took us so long to get around to it, but I'm opening a couple of PRs that should move the 'edit' button _above_ the content rather than below it for logged in users in the reading interface of all Pressbooks themes.

**Comment by cogdog** [comment]
Github is never having to say you're sorry, Steel!

I actually thought having it top and bottom might be useful... I would kept he bottom one, I just always thought the admin bar was a place to put the Edit button like native WordPress, I guess somewhere there is a hook to remove that menu item. I've done a few admin menu bar mods for other purposes (reason number 561 for loving WordPress)

**Comment by SteelWagstaff** [comment]
I released a new version of Aetna with the edit button padding changes. Will merge updates to Aldine and pressbooks-book and test further today.

**Comment by SteelWagstaff** [comment]
Tested and working as expected on dev nextworks. Ready for release.
