### ISSUE TITLE
Open tickets to resolve PHP8.1 compatibility issues in all relevant repos

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#436]
We are requiring PHP8.0 in our upcoming releases of all repos and adding PHP8.1 to our test matrices. In all repos where we have warnings or test failures, we should create tickets for fixing these issues.

See https://www.php.net/manual/en/migration81.incompatible.php 

DoD: Any repo where PHP8.1 tests aren't passing or where we have compatibility warnings has an issue created to make compatible with PHP8.1

**Comment by SteelWagstaff** [comment]
Opened issues in
1. pressbooks/pressbooks: https://github.com/pressbooks/pressbooks/issues/3044
2. pressbooks/lti-provider-1p3: https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/272

**Comment by cmurtagh** [comment]
FYI Steel, we had removed this from the current sprint backlog because there were concerns about the sprint velocity and that PHP 8.1 wasn't a blocker for any other tasks.

**Comment by SteelWagstaff** [comment]
Thanks @cmurtagh -- when I talked with @richard015ar yesterday about sprint goals, he explained which issues you removed and why. He also told me he was almost finished with bug fixes and issues he felt qualified to work on and we discussed adding a few more issues into the sprint backlog. This was one of them.

**Comment by cmurtagh** [comment]
Coolio! Just wanted to be sure you knew why it was't there. I too might be looking into the backlog for Ops tasks!

**Comment by SteelWagstaff** [comment]
Reviewed all our repos and only two of them have compatibility warnings with PHP 8.1. tickets have been opened here: https://github.com/pressbooks/pressbooks/issues/3044 + https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/272.
