### ISSUE TITLE
Readily display Pressbooks plugin versions e.g. for H5P, Hypothes.is, etc.

### ISSUE THREAD

**Issue by Waltonl333** [pressbooks/ideas#437]

**Comment by SteelWagstaff** [comment]
@Waltonl333 this should be available to you (as a network manager) from the diagnostics page of your network: `https://YOURNETWORKURL/wp/wp-admin/options.php?page=pressbooks_diagnostics`. In your case, it should be https://westernsydney.pressbooks.pub/wp/wp-admin/options.php?page=pressbooks_diagnostics

**Comment by Waltonl333** [comment]
Thanks, Steel

BTW - has there been any update on being able to add Pressbooks to the Alma platform?

Regards

Lucy Walton | Scholarly Publishing Consultant
Library Research Services, Library (On-campus Mon-Wed: 02 9852 5108)
https://uws.zoom.us/j/4414191091

Western Sydney University
Locked Bag 1797 Penrith NSW 2751 Australia
westernsydney.edu.au

[WSU_Logo_hex_142x56px_email signature]<http://www.westernsydney.edu.au/>

From: Steel Wagstaff ***@***.***>
Sent: Tuesday, 29 November 2022 8:43 AM
To: pressbooks/ideas ***@***.***>
Cc: Lucy Walton ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [pressbooks/ideas] Readily display Pressbooks plugin versions e.g. for H5P, Hypothes.is, etc. (Issue #437)


@Waltonl333<https://github.com/Waltonl333> this should be available to you (as a network manager) from the diagnostics page of your network: https://YOURNETWORKURL/wp/wp-admin/options.php?page=pressbooks_diagnostics

-
