### ISSUE TITLE
Track clones of books I've published

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#442]
As an author or network manager, I want to know when others clone openly licensed books that I have published so that I can measure the impact and reach of my work, and potentially notify people who have adopted/adapted my book when the source book has updates. 

These things would be helpful:
- [x] pressbooks/pressbooks#3055
- [x] pressbooks/pressbooks#3056
- [x] pressbooks/pressbooks#3057
- [x] pressbooks/pressbooks-network-analytics#271

**Comment by cmurtagh** [comment]
There are some security concerns here. We'll need to prevent bad actors from hitting up against the API with potentially malicious URLs.
