### ISSUE TITLE
Require PHP8.1 in all repos & bedrocks

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#454]
Create new releases of our plugins & themes which require PHP8.1. When we do this, look for ways to improve and make it easier to bump PHP versions in the future.

## Notes
For each repo, we should:
1. Update PHP compatibility rule in phpcs.ruleset.xml
2. Update PHP requirement in composer.json and run composer update -W
3. Add PHP 8.2 to CI pipelines and set PHP 8.1 & WordPress 6.1.1 as non-experimental matrix combination
 
Repos that need to be updated:

### Plugins
- [x]  Pressbooks https://github.com/pressbooks/pressbooks/releases/ 
- [x]  Excalibur  https://github.com/pressbooks/excalibur/releases/
- [x]  Pressbooks BISAC https://github.com/pressbooks/pressbooks-bisac/releases/
- [x]  Pressbooks CAS SSO  https://github.com/pressbooks/pressbooks-cas-sso/releases
- [x]  Pressbooks eCampusOntario https://github.com/pressbooks/pressbooks-ecampus-ontario/releases
- [x]  Pressbooks LTI Provider 1.3 https://github.com/pressbooks/pressbooks-lti-provider-1p3/releases
- [x]  Pressbooks Network Analytics https://github.com/pressbooks/pressbooks-network-analytics/releases
- [x]  Pressbooks Network Catalog https://github.com/pressbooks/pressbooks-network-catalog/releases
- [x]  Pressbooks OIDC SSO https://github.com/pressbooks/pressbooks-oidc-sso/releases
- [x]  Pressbooks Plugins Config: https://github.com/pressbooks/pressbooks-plugins-config/releases/
- [x]  Pressbooks SAML SSO https://github.com/pressbooks/pressbooks-saml-sso/releases
- [x]  Pressbooks Stats https://github.com/pressbooks/pressbooks-stats/releases
- [x]  Pressbooks Whitelabel https://github.com/pressbooks/pressbooks-whitelabel/releases
- [x]  Pressbooks Auth https://github.com/pressbooks/pressbooks-auth/releases/
- [x]  Pressbooks VIP https://github.com/pressbooks/pressbooks-vip/releases/
- [x]  Pressbooks selfe https://github.com/pressbooks/pressbooks-selfe/releases/
- [x]  Pressbooks Biblioboard OAuth https://github.com/pressbooks/pressbooks-biblioboard-oauth/releases
- [x]  Pressbooks Client Marketing https://github.com/pressbooks/pressbooks-client-marketing/releases

### Themes
- [x]  Pressbooks-book https://github.com/pressbooks/pressbooks-book/releases
- [x]  Aldine  https://github.com/pressbooks/pressbooks-aldine/releases/
- [x]  Pressbooks Librarian https://github.com/pressbooks/pressbooks-librarian/releases

### Other
- [x]  PB CLI https://github.com/pressbooks/pb-cli/releases

### Bedrocks
- [x]  pressbooksedu-golden-bedrock
- [x]  pressbookspublic-bedrock
- [x]  pressbookspub-bedrock
- [x]  client-bedrock
- [x]  wisc-bedrock

After we make these changes, we will no longer guarantee support for PHP 8.0.

**Comment by richard015ar** [comment]
Included in the sizing is an improvement to centralize / simplify the php version changing process
