### ISSUE TITLE
Replace dashicons with heroicons

### ISSUE THREAD

**Issue by arzola** [pressbooks/ideas#456]
### Feature Description

Heroicons offers a fresh look and feel and it would be helpful to being able to use them seamlessly as if they were the regular dashicons

### Feature Use Case

Just to improve the look and feel without disrupt the current behaviour

### Other Notes

Something like: https://giteroptimized.com/how-to-remove-dashicons-in-wp/

**Comment by SteelWagstaff** [comment]
Closing in favor of https://github.com/pressbooks/pressbooks/issues/3183
