### ISSUE TITLE
add citation metadata

### ISSUE THREAD

**Issue by meganlavengood** [pressbooks/ideas#467]
### Feature Description

Pressbooks page metadata could/should be structured as set out in this guide from Zotero: https://www.zotero.org/support/dev/exposing_metadata 

### Feature Use Case

Lots of academics use Zotero for keeping track of research; this would help with that.

**Comment by SteelWagstaff** [comment]
hi @meganlavengood closing this idea because it already exists! Pressbooks does currently expose structured metadata for Zotero (and other citation management tools) to consume by default. This has been a supported feature since Pressbooks 5.7.0 (released in early 2019).
