### ISSUE TITLE
Changing noun "book" in "read book" to another word.  

### ISSUE THREAD

**Issue by scfinlay** [pressbooks/ideas#469]
I have had multiple faculty from multiple departments request the ability to change the noun "book" in "read book" to something else.  Is this possible?

**Comment by MichSpieler** [comment]
This feature was also requested by a user in this [ticket](https://pressbooks.zendesk.com/agent/tickets/20631) (link for internal use).

**Comment by scfinlay** [comment]
It says the page I requested doesn't exist. Hm.

Stephen Craig Finlay
OER and STEM Librarian
UNO Libraries
(402)554-3211
________________________________

**Comment by MichSpieler** [comment]
> It says the page I requested doesn't exist. Hm. 

> 

In case you are referring to the link in my previous comment, it is a link that is only accessible for Pressbooks Support staff. Thus the bracket saying "link for internal use".

**Comment by scfinlay** [comment]
Ah, that makes sense

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SteelWagstaff** [comment]
Closing in favor of https://github.com/pressbooks/ideas/issues/397 (duplicate)
