### ISSUE TITLE
Allow cloning into an existing book (overwriting content)

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#48]
### Feature Scope

- [ ] Accessibility and inclusivity
- [X] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

Now we can clone a book in a new and fresh book.

I use https://premium.wpmudev.org/project/cloner/ where I can close in a new fresh book or to delete an old one by writing the new information over the old book.

![cloner-clone-site](https://user-images.githubusercontent.com/3929177/37555554-4ea53d5e-29e9-11e8-8c68-f7a47f7795af.png)

A feature to consider for the future maybe.

### Feature Use Case

Users that whant to keep the same url and to change the book for some reason by importing maybe a new version or a different version of the same book or other book.

### Other Notes

https://discourse.pressbooks.org/t/cloning-of-books/265

**Comment by SteelWagstaff** [comment]
@colomet this is already possible with the import from webpage or Pressbooks webbook option -- if you enter the URL of a Pressbooks title, you can clone all or part of that book into an existing title. We will not be adding the ability to overwrite existing content via cloning operation anytime soon, so closing this ticket for now.
