### ISSUE TITLE
AMP for pb

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#50]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [X] Integration with third-party services

### Feature Description

I know maybe is not a good test for PB as the content is not updated all the time, but I send the link as information. Maybe we can make PB better for mobiles with that.

    
### Feature Use Case

Google Search indexes AMP pages to provide a fast, reliable web experience. When an AMP page is available, it can be featured on mobile search as part of rich results and carousels. For more information on the benefits of using AMP, see the AMP Project case studies.

### Other Notes

https://www.ampproject.org/

https://discourse.pressbooks.org/t/amp-test-for-a-pb-installation/230

**Comment by greatislander** [comment]
We won't be doing this. See: http://ampletter.org/?lang=es
