### ISSUE TITLE
 Copyright Notice: if is long, makes to long the footer

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#51]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [X] Book themes
- [ ] Integration with third-party services

### Feature Description

Take a look my footer, where I have Copyright Notice:

http://open.books4languages.com/grammarb1es/

What if the Copyright Notice is a link to a different page, like to the page with the Front Matter Type Copyright Notice assigned in the Front Matter CPT ?

Also that is the good place as in that way we can export with the pdf in the correct place or to start to read the book online and to read that.

### Feature Use Case

If the information of the Notice is long, the footer is too long, some times even longer than the page.

### Other Notes

https://discourse.pressbooks.org/t/copyright-notice-if-is-long-makes-to-long-the-footer/281

**Comment by SteelWagstaff** [comment]
We won't be changing this in the near future. The workaround proposed (linking to a copyright notice elsewhere in the book), seems to offer a decent alternative for very long copyright statements. Closing for now.
