### ISSUE TITLE
Add University of Colorado Anschutz Medical Campus to list of institutions

### ISSUE THREAD

**Issue by JohnMcLeod13** [pressbooks/ideas#510]
Add University of Colorado Anschutz Medical Campus (https://www.cuanschutz.edu/) to list of institutions in Book Info.

Request from Network Manager for Colorado shared network. https://pressbooks.zendesk.com/agent/tickets/23342

**Comment by cmurtagh** [comment]
Thomas' PR has been merged, and will go out in the next Presbooks release (likely when Os is back on Monday).

**Comment by tw77** [comment]
Ready for release, appears as expected on dev.
