### ISSUE TITLE
Editing the Book Menu across an entire site

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/ideas#56]
### Feature Scope

It would be nice to be able to edit the top menu for every book homepage across an entire site or edit the footer.

Use case:

(As some of you may know) I recently installed the non-commercial Prince XML to do my document conversion to PDF. One of the requirements of the non-commercial license is to have a link to Prince XML on the page where the PDF will be downloaded. On my root homepage, I have added a link in the top right corner as part of the header and footer menus.

However they actually download the PDF from the book site page. I wish I could easily edit the menu on the book page across my entire network, and/or edit the footer so where it says "Powered by Pressbooks" I could add a new line underneath that says document conversion by Prince XML, or perhaps in the menu next to "Open Source | Open Textbooks | Open Publishing | Learn More

I will also add the required language that they want inside the PDF to the back of the copyright page.

I just really appreciate that Prince has a non-commercial license, and want to credit them as much as possible in the same spirit.

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [x] Import/export formats
- [ ] Authoring tools
- [x] Book themes
- [x] Integration with third-party services

**Comment by greatislander** [comment]
Hi @beckej13820, you can use these filters to add the link to the book footer:

https://github.com/pressbooks/snippets/blob/master/webbook-theme-hooks/hooks.php#L23-L31

Add the text you need and save a file to `wp-content/mu-plugins/footer-text.php` (or some other filename).

Editing menus for all books across a network is not really scaleable (on Pressbooks.com, for example, we have over 60,000 books). A filter that outputs content in a specified location is the better way and I'd encourage you to use one of these.
