### ISSUE TITLE
Bookmark the chapter for later

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#58]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [X] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To have a bookmark functionality. It will allow to the readers to save a chapter and to find it easy later.

### Feature Use Case

A student need to study a subject, and the information about the subjec is in several chapters in all of the book. With a bookmark buttom he can save the content and later to find it and keep reading. Otherwise, some times if the book have too many pages, is  too hard to find.

### Other Notes

Also in the future he can just to print or export those bookmark chapters. Not the full book or parts or randomly chapters.

**Comment by SteelWagstaff** [comment]
Won't implement
