### ISSUE TITLE
To export selected chapters or parts together

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#59]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [X] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To be able to export a selection of chapters or parts as a book.

### Feature Use Case

Some times we need a selection of content, so we can create our own personaliced book by just selecting those parts or chapters that we need.

### Other Notes

Now we can export the full book, soon independent chapters and parts, why not randomly content?, like wikipedia: https://en.wikipedia.org/w/index.php?title=Special:Book&bookcmd=book_creator&referer=Lady+Gaga

**Comment by SteelWagstaff** [comment]
@colomet book admins are currently able to export selected parts/chapters from books by customizing what chapters are selected for export before performing an export operation. With the changes coming to the export page in 5.7, I think the idea as you describe it here should be even easier.

**Comment by colomet** [comment]
I will review the process after you release 5.7. 

thanks you.
