### ISSUE TITLE
Network statistics

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#60]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [X] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To have statistics about the network

### Feature Use Case

To have information, knowing how many books, parts, chapters, users, administrators, editors....

### Other Notes

https://en.wikipedia.org/wiki/Special:Statistics

**Comment by SteelWagstaff** [comment]
@colomet some of these are available through https://github.com/pressbooks/pressbooks-stats. Other usage information can be obtained through Google Analytics integration: https://networkmanagerguide.pressbooks.com/chapter/configuring-google-analytics-for-pressbooks/. For enterprise customers, we provide additional dashboards with more user and book information (see chapters 4-6 in the Network Manager guide). We won't be adding more to the open source Pressbooks instance in the near future, so closing this ticket for now.
