### ISSUE TITLE
Lock latest Export files at one version for the share section of the home page

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#64]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [x] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To make available on the home page a selected version of the export book, not the last one.
Is necesary something as in the export settings the Lock Theme functionality for the css.

So, in each export, a buttom for the lock of the version as the download version of the book. It will be always available, no matter how many more times we export a book.

### Feature Use Case
 We can Share Latest Export Files 

> (I would like the latest export files to be available on the homepage for free, to everyone)

The problem is, we offer the last exportation. What if we have a preview of the book with just a selection of pages and then the full book. It would be nice if we can offer the preview of the book, not the full book, so we can export anytime we wish the new full version of the book, or more versions for differetn purposes, but in the download section of the book cover , just the preview  (a selected version) would be available.

**Comment by SteelWagstaff** [comment]
Thanks for this suggestion. Closing in favor of https://github.com/pressbooks/pressbooks/issues/2182, which is in our backlog.
