### ISSUE TITLE
Export page information just for Admins or SuperAdmins

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#65]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [X] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To hide the information if a user is not Admin and/or SuperAdmin

![captura de pantalla 2018-04-03 a las 15 30 55](https://user-images.githubusercontent.com/3929177/38252356-3140dec6-3754-11e8-99cd-60e4b84a0e32.png)
![captura de pantalla 2018-04-03 a las 15 31 21](https://user-images.githubusercontent.com/3929177/38252358-315e729c-3754-11e8-98fe-c0a14631dc62.png)

### Feature Use Case

People have questions if they see a warming. And I do not think they have to know if something is missing or not.

The same with the export types, if they are not available, maybe is better if we do not show to the collaborators.

**Comment by SteelWagstaff** [comment]
We won't be changing this in near future. You should be able to suppress yourself on a self-hosted network, if desired.
