### ISSUE TITLE
Integrate Book theme with a membership plugin

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#66]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [X] Book themes
- [x] Integration with third-party services

### Feature Description

To be able to use a membrship plugin with PB.

### Feature Use Case

Some people whant to monetice the platform. Or to restric to specifical situations or to hide some specifical content to specifical people. With a membership plugin we can choose what to make available to specifical people.

### Other Notes

We found Restrict Content Pro  (RCP) to be one of the most easy to use membership plugin. It is also developer friendly, and comes with a great set of features that are perfect for all kind of membership websites. 

Restrict Content Pro is a powerful contender for the title of the best membership plugin for WordPress. It is created by same team that’s behind the popular Easy Digital Downloads and AffiliateWP plugins 

(So in the future if somebody whant to create a marketplace for books in site 1, all the plugins can be integrated)

- https://www.wpkube.com/restrict-content-pro-review/
- https://github.com/restrictcontentpro/restrict-content-pro/releases
- https://docs.restrictcontentpro.com/article/1595-restricting-content-in-template-files

We can restrict or not:

- The download of books
- The acces to content just for selected users (roles, levels, memberships)
  - The acces to parts
  - The acces to chapters
  - The acces to create new books
  - The acces to widgets
  - The acces to ....

**Comment by colomet** [comment]
We need such development. A simple one.  Maybe we can after the creation, send to github.

**Comment by greatislander** [comment]
Anyone who wants this feature needs to (and is welcome to) invest in developing it themselves, as it does not fall within the scope of the core team's goals for Pressbooks.

**Comment by colomet** [comment]
My question is: Do you would like to have it in the core of the theme? 

- If so, I could develop a neutral simple version. (And later to extend with particularities in my child theme)
- If not because is a child theme/plugin issue, not an development for the PB Core, I will just to develop my own child theme. (Wich is faster for us. Later, we can offer our child from github too, but it would be too specifical for us, maybe)

**Comment by greatislander** [comment]
No, we don’t want it in core.
