### ISSUE TITLE
Related chapters

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#67]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [X] User interface (reading)
- [ ] Import/export formats
- [X] Authoring tools
- [X] Book themes
- [ ] Integration with third-party services

### Feature Description

Related books in the bottom of the content.

### Feature Use Case

A fiction book do not need that feature, maybe. But a educational book may have related content in other chapter from the same book or from a different book also.

### Other Notes

 If we could have a place where we could write (if we need) 1-4/6 links . Later, those links would be on the bottom of the content (we will see the chapter name and the number but the number would be a link)

![captura de pantalla 2018-04-04 a las 11 44 05](https://user-images.githubusercontent.com/3929177/38364775-33bc0414-38da-11e8-94a4-c84568a01216.png)

**Comment by colomet** [comment]
I do have views on my site, but not interaction, we need relations with content in order to keep the users reading the books.

**Comment by SteelWagstaff** [comment]
Won't implement
