### ISSUE TITLE
Reading time for a chapter

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#68]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [x] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [x] Book themes
- [ ] Integration with third-party services

### Feature Description

1. At the top of each chapter we could have an estimated read time for the chapter.
3. At the top of each part, we could have an estimated read time for the chapters of the part.
5. In the Book cover page, we could have an estimated read time for the chapters of the book.

### Feature Use Case

People can have an estimation about how long does it take to read the chapter. And more important, we can have in the book cover page a total reading time for the full book. Or parts.

So teachers can know if is apropiate for the class or not a chapter or part.

### Other Notes
Read time must be based on the average reading speed of an adult (roughly 275 WPM). We take the total word count of a post and translate it into minutes, with an adjustment made for images.

- [Medium](https://help.medium.com/hc/en-us/articles/214991667-Read-time)
- [More info](http://ezinearticles.com/?What-is-the-Average-Reading-Speed-and-the-Best-Rate-of-Reading?&id=2298503)

**Comment by alminervini** [comment]
Yes, please make reading times a reality. This would be super helpful to my students who work better with incentives and knowing their time capacity and constraints on time. Thank you!! :)

**Comment by SteelWagstaff** [comment]
I don't think we'll make this part of core Pressbooks. For folks interested in this, you may want to consider a plugin like https://wordpress.org/plugins/reading-time-wp/
