### ISSUE TITLE
Automated Link Attribution with Copy-Magic-Paste

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#71]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [X] Book themes
- [ ] Integration with third-party services

### Feature Description

Each time a user copy and paste a text, automatically they copy the link of the page.

### Feature Use Case

 We've all seen it: Someone helps themselves to your awesome content and pastes it onto their own website without even mentioning the source. 

Wouldn't it be generous of us to do the work for them? Wouldn't it be ideal if their copy and pasted content automatically linked back to your site?

### Other Notes

[copymagicpaste-a-script-and-easytouseguide-to-customize-the-copyevent-on-your-website](https://moz.com/ugc/copymagicpaste-a-script-and-easytouseguide-to-customize-the-copyevent-on-your-website)

**Comment by Verdem-crypto** [comment]
where i can download it?

**Comment by colomet** [comment]
You can copy and paste the code in your theme or plugin maybe.
```

<!--
-				ADDED: Add a #copyright notice to the clipboard when someone copies a text from the website.
-
-				@SINCE
-				@LINK https://stackoverflow.com/questions/2026335/how-to-add-extra-info-to-copied-web-text
-				@LINK https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event
-				@LINK https://www.wpbeginner.com/wp-tutorials/how-to-add-a-read-more-link-to-copied-text-in-wordpress/
- 	  const pagelink = `\n\nSource: © ${document.location.href}`;
-->

<?php
if ( !wp_is_mobile() ) {
	if ( !is_user_logged_in() ) { ?>
	<script type="text/javascript">

	document.addEventListener('copy', (event) => {
	  const pagelink = `\n\nSource: <?php the_title(); ?> © <?php echo wp_get_shortlink(get_the_ID()); ?>`;
	  event.clipboardData.setData('text', document.getSelection() + pagelink);
	  event.preventDefault();
	});

	</script>
<?php }
}
?>
<!-- END CODE -->
```

**Comment by colomet** [comment]
If you do not like to show the URL with the id of the page, change the const pagelink =

`const pagelink = `\n\nSource: © ${document.location.href}`;`

**Comment by sudarshan-gautam** [comment]
anyone can detail me about the code? I am using WordPress and where to paste it?

**Comment by colomet** [comment]
Example of tutorial about how to do it: 
https://www.wpbeginner.com/plugins/how-to-easily-add-custom-code-in-wordpress-without-breaking-your-site/

**Comment by SteelWagstaff** [comment]
Closing as we won't be implementing this is Pressbooks core in near future, but open source users are welcome to read this thread for ideas about implementation on their own.

**Comment by streats** [comment]
Hi - I found out about Copy-Magic-Paste from this [2015 article on Moz.com](https://moz.com/blog/copymagicpaste-a-script-and-easytouseguide-to-customize-the-copyevent-on-your-website). Is it the same thing? Is Squarespace supported? I'm helping a friend out who is being copied left right and center (entire pages) by competitors and I wanted to see if this might help provide at least a small deterrent. Thanks!
