### ISSUE TITLE
Heading of tables. Different style

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#72]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [X] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [X] Book themes
- [ ] Integration with third-party services

### Feature Description

To have a different style for:

- the headings of tables
- the footer of tables

### Feature Use Case

Better design

### Other Notes

[https://discourse.pressbooks.org/t/headings-for-tables/443](https://discourse.pressbooks.org/t/headings-for-tables/443)

**Comment by SteelWagstaff** [comment]
Too vague. Won't implement.
