### ISSUE TITLE
McLuhan neutral style

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#73]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [X] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [X] Book themes
- [ ] Integration with third-party services

### Feature Description

To have a neutral style that works in any situation.
The italics in the current style are hard to see. 

### Feature Use Case

We have to have the base book theme as neutral as possible. Then, if we need specifical details, we will create  a child theme.

A newspaper style is the most neutral of all of them maybe. So ifread from the web version or to print a page from the web site, we will have a clear text.

They use  georgia (the most of them) and other stilistic details like the color of the ink.

### Other Notes

I think [The Guardian](https://www.theguardian.com/world/2018/apr/09/syrian-airbase-near-homs-hit-by-air-strikes-state-tv-says) or [The New York Times](https://www.nytimes.com/2018/04/04/climate/animals-seasons-mismatch.html?rref=collection%2Fsectioncollection%2Fclimate&action=click&contentCollection=climate&region=stream&module=stream_unit&version=latest&contentPlacement=7&pgtype=sectionfront) are good examples as are two of the most importand and beautiful newspapers. Also are good examples as I´m sure they spend money with the creation of the style, so we just have to copy the most of it.

**Comment by SteelWagstaff** [comment]
Thanks for the suggestion, @colomet. We're not changing the default style of McLuhan because it was built to specification for a client. Closing this idea.
