### ISSUE TITLE
Provide ability to give contributors access to selected parts/chapters of book

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#74]
### Feature Scope

- [ ] Accessibility and inclusivity
- [X] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To give acces to parts (and the chapters of the part) to contributors

### Feature Use Case

Some times we have content created, but we have to update the content, to give acces to contributors to parts would help the authors to create content.

So, a contributor can spelling mistakes, organice content, update images or other issues. Without being cappable of deleting the post or touching other content.

**Comment by SteelWagstaff** [comment]
@colomet contributors should be able to edit chapters which they are the ‘owners’ of: https://guide.pressbooks.com/chapter/chapters/. There’s a bug we need to fix though: https://github.com/pressbooks/pressbooks/issues/2131. Closing this issue in favor of that one.
