### ISSUE TITLE
Duplicate content after clone

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#75]
### Feature Scope

- [ ] Accessibility and inclusivity
- [X] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description
To have from the clone books a link to the original book. And to be able to not to have it if the content is going to be modify and is not anymore a "copy" of the original book, instead is base on.

### Feature Use Case
Some times we have a template and later we use in our books, so all the books of the installation follow the same style, such situation change nothing but some times we clone a full book and we just use in our installation.

if we clone a book, we have duplicate content, so in order allow to receive to the original book the apropiate gredit on google (to be the first or only in the google search) is good to have a link to the original content from the child books

### Other Notes
[Using rel=”canonical” links](https://yoast.com/duplicate-content/#rel-canonical)

**Comment by colomet** [comment]
Update: IsBaseOn is property is created.

To be able to not to give credit is still missing. Or to give credit manually.

**Comment by SteelWagstaff** [comment]
Cloned books automatically receive a statement on the book info page indicating where the book has been cloned from. There's no way to remove this statement from the GUI itself, but it can be done by editing the database directly. We're also interested in better tools for textual citation: https://github.com/pressbooks/ideas/issues/223. Closing this issue as it's been partially fixed and other parts are now duplicated by other tickets.
