### ISSUE TITLE
Media settings

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#76]
### Feature Scope

- [ ] Accessibility and inclusivity
- [X] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To have relation with the images sizes and the theme content width.

### Feature Use Case

If we upload a picture to a site, the sizes of the images would be 300 and 1024 px with. But the width of the content section is 540px (narrow), 720px (Standard) and 864px (wide) the images are not optimised.

We have a 540px canvas and the picture would be or 1024 (so too big) or 300 (so, pixelate). No a good option.

### Other Notes

A faster way would be to have default sizes of 400, 700 and 850px width. Is not flexible but it will work better I guess.

But is a situation to analice.

**Comment by SteelWagstaff** [comment]
As a network manager, you can already define the default thumbnail sizes used when media files are uploaded to your WordPress/Pressbooks network by visiting `https://YOURNETWORK.URL/wp-admin/options-media.php`. If you decide to change your default thumbnail sizes, you can use this plugin to regenerate them: https://wordpress.org/plugins/regenerate-thumbnails/.
