### ISSUE TITLE
Take it to the last read page for the subscriber

### ISSUE THREAD

**Issue by johnpeterm** [pressbooks/ideas#78]
Allow subscribers to login for reading book, when the user come back and login  again, it should take it to the page where they left last reading

### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [x] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

**Comment by SteelWagstaff** [comment]
@johnpeterm Thanks for the suggestion. Closing as this would probably require setting cookies to remember logged in user behavior that we don't want to add to Pressbooks at this time.
