### ISSUE TITLE
WhatsApp Share button

### ISSUE THREAD

**Issue by johnpeterm** [pressbooks/ideas#80]
In the social media share button of books, adding "WhatsApp" will be great advantage since WhatsApp is widely used social media platform

### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [x] Integration with third-party services

**Comment by SteelWagstaff** [comment]
We're not planning to add a share on What's App button anytime soon. Thanks for request!
