### ISSUE TITLE
To share contributors with all the books

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#82]
### Feature Scope

- [ ] Accessibility and inclusivity
- [X] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To have an option that allow to use the same names in all the books 

### Feature Use Case

Some times a team of people do the  most of the work (maybe not the author but the reviewer, illustrator, editor ...), so by sharing the same names (if activated) in all the books will make the process much faster

### Other Notes

![captura de pantalla 2018-05-03 11 31 06](https://user-images.githubusercontent.com/3929177/39569589-f4ab49ae-4ec5-11e8-98d7-2bfda1e6e88d.png)

**Comment by SteelWagstaff** [comment]
Closing as this issue has been duplicated by https://github.com/pressbooks/pressbooks/issues/1824
