### ISSUE TITLE
To change tagline from book info

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#85]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [X] Book themes
- [ ] Integration with third-party services

### Feature Description

We need to be able to change the tagline from book info
![captura de pantalla 2018-05-03 13 27 41](https://user-images.githubusercontent.com/3929177/39595049-aa3d94fa-4f0e-11e8-996c-94cffe170e43.png)

### Feature Use Case

If we share the book on facebook or .. the information is available to the people, as it have not easy acces, we have the default sentence

### Other Notes

![captura de pantalla 2018-05-03 20 15 41](https://user-images.githubusercontent.com/3929177/39595108-db7ad2bc-4f0e-11e8-9b56-2efc9feadd3e.png)

**Comment by SteelWagstaff** [comment]
@colomet you can edit this manually by visiting `https://YOURNETWORK.URL/wp-admin/network/site-settings.php?id=#` with the ID number for your book inserted in the place of `#`. Closing this issue, as we've added a similar feature to our product backlog: https://github.com/pressbooks/ideas/issues/349
