### ISSUE TITLE
To change the order of the contributors in book info

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#89]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [X] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To change the order of the contributors

### Feature Use Case

Some times, we have new contributors and we just need to ad the new one. If we have so many and we do not like the order, we have to delete all of them and to find them again...

### Other Notes

![captura de pantalla 2018-05-07 20 12 39](https://user-images.githubusercontent.com/3929177/39718214-ea7b97cc-5235-11e8-94aa-4b58596b1e3d.png)

**Comment by greatislander** [comment]
We will be addressing this.
