### ISSUE TITLE
Contributor field adaptable

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#90]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [X] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To have the contributor field in book info and in the editor text adaptable

### Feature Use Case

It would be possible to chante the place, and to write people more efficient.

### Other Notes

![captura de pantalla 2018-05-11 a las 9 14 13](https://user-images.githubusercontent.com/3929177/39911453-bb88b044-54fb-11e8-9d05-d8b395422e65.png)
![captura de pantalla 2018-05-11 a las 9 16 45](https://user-images.githubusercontent.com/3929177/39911552-2087958c-54fc-11e8-8108-e7bde0094702.png)

**Comment by greatislander** [comment]
We will be addressing this.
