### ISSUE TITLE
Tooltips 

### ISSUE THREAD

**Issue by NMSalmon** [pressbooks/ideas#91]
### Feature Scope

- [x] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [x] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description
We'd like to be able to add tooltips to define terms within a page (independent of a glossary tool.) @SteelWagstaff and I have been experimenting with different tooltip plugins on our dev instance. We like the way that the [Simple Tooltips](https://www.clevelandwebdeveloper.com/wordpress-plugins/simple-tooltips/) Wordpress plugin operates because it allows readers to select the text or image contained within the tooltip bubble. We especially liked the way that [Nicolas Hoffmann's jQuery Simple Tooltip plugin](https://a11y.nicolas-hoffmann.net/simple-tooltip/) emphasizes accessibility.

The first screenshot below shows the Simple Tooltips Wordpress plugin, while the second illustrates the ability to highlight and copy text within the tooltip bubble:

![simple tooltips example](https://user-images.githubusercontent.com/35341860/39937980-04afb13a-5517-11e8-88ee-053022f3363d.png)![simple tooltips text select example](https://user-images.githubusercontent.com/35341860/39937981-04c4c4a8-5517-11e8-8f06-3068ca018c46.png)

### Feature Use Case
This should benefit anyone who would like to explain a term in a way that is specific to a single page in their text. 

For instance, many language instructors incorporate vocabulary explanations into their assignments and would like to gloss words or phrases on the page. (The ability to do so in writing is highest-priority, but the option to include explanatory images or even audio clips with pronunciations would be nice.) These instructors would like the choice to keep the tooltip explanations of some phrases distinct from the definitions they might provide in a glossary for their textbook as a whole. 

(A specific example: One instructor noted that she needed to explain the specific connotation of the phrsas "il faut" in a French poem. The textbook she is creating includes multiple different uses of "il faut," so the tooltip text needs to be independent of the glossary and specific to this poem. In contrast, the [CM Tooltips Glossary Plugin](https://wordpress.org/plugins/enhanced-tooltipglossary/) we are currently using--(pictured below)--allows for users to choose either to gloss all instances of a word or phrase in the entire text or just the first instance in a chapter, neither of which are helpful for this use case.)

![sample glossary tooltip in french assignment](https://user-images.githubusercontent.com/35341860/39938548-ef422d26-5518-11e8-9d5d-1a816fbc38e6.png)

**Comment by SteelWagstaff** [comment]
@greatislander and @connerbw -- we think this could go along way towards helping us replace the nonstandard CM Tooltip plugin we're currently using at Wisconsin. If we had a simple, elegant tooltip solution in place, we'd be happy to wait for the official PB glossary tool on the development roadmap, FWIW.

**Comment by SteelWagstaff** [comment]
FWIW, the Simple Tooltips plugin for WordPress appears to be based on this jQuery tooltips plugin: https://github.com/stefangabos/Zebra_Tooltips/
