### ISSUE TITLE
To have a catalog image ready for different uses

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#92]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [X] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [X] Integration with third-party services

### Feature Description
To have images for the books with the same dimensions of the facebook posts 

### Feature Use Case
We need to have a image for the catalog page, so as the space for the catalog page is not good for the book cover, maybe we can have a secondary image that works and it could be used also for social profiles like facebook

We publish the image at 1.200x630px. Later PB use a tiny version and by sharing with Facebook the orignal image is shared.

Current situation
![captura de pantalla 2018-05-23 a las 15 42 02](https://user-images.githubusercontent.com/3929177/40428508-befeebcc-5ea0-11e8-8717-5de89cf4bf91.png)

Example with an image
![captura de pantalla 2018-05-23 a las 15 42 02](https://user-images.githubusercontent.com/3929177/40428648-0ba12e7c-5ea1-11e8-9ff9-a7fdf81f9749.png)

### Other Notes
Maybe we can conect that issue with https://github.com/pressbooks/ideas/issues/86

**Comment by SteelWagstaff** [comment]
No longer relevant with new catalog.
