### ISSUE TITLE
Add export to format APPS BOOK. and Shortcodes in themes and content

### ISSUE THREAD

**Issue by rseales** [pressbooks/ideas#94]
### Feature Scope

- [ ] Accessibility and inclusivity
- [x ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [x ] Import/export formats
- [ ] Authoring tools
- [x ] Book themes
- [ ] Integration with third-party services

### Feature Description

To convert Book content to APPs Mobile with  wordpress Plugings for this work, I. E. Mobilize,  WPTouch, MAB Mobil APP Builder, etc...

**Comment by greatislander** [comment]
Hi @rseales, we won't be doing this in the foreseeable future.
