### ISSUE TITLE
new export option: with or without the cover image

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#95]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [X] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To be able to export the book and to have not the image in the ebook, pdf...

### Feature Use Case

Some times we need a simple lite version of the book. (to send in an email or so...) Without the cover image, we decrease 2 mb the size of the pdf. An option would be the best. So if is a lite version, no image if is a full version, image. Also it will decrease the amount of required hard drive for the backups as all the testing pdfs would  have no images.

**Comment by greatislander** [comment]
The cover image is not added to PDF exports by default. I'm not clear on the use case for EPUBs with no cover image. If you compress the image properly you should have manageable sizes. We intend to enable the embedding of a cover image in a PDF for digital distribution; see https://github.com/pressbooks/pressbooks/issues/591
