### ISSUE TITLE
post editor - navigation keyboard

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#98]
### Feature Scope

- [ ] Accessibility and inclusivity
- [X] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

To change the pages with the keyboard arrows.

![captura de pantalla 2018-06-28 17 24 36](https://user-images.githubusercontent.com/3929177/42044006-24119780-7af8-11e8-8029-d3ee0f298055.png)

### Feature Use Case

Some times we have to review all the pages, that makes faster the revision.

**Comment by SteelWagstaff** [comment]
Won't implement
