### ISSUE TITLE
Most read book on the catalog page

### ISSUE THREAD

**Issue by johnpeterm** [pressbooks/ideas#99]
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [x] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [ ] Book themes
- [ ] Integration with third-party services

### Feature Description

On the catalog page, may be we can have tab or in the filter for "Most Read Books" and we can have list of the books on the order of mostly read.

### Feature Use Case

This feature will help the reader to easily identify popular books

**Comment by gunha** [comment]
Pressbooks allows for google analytics to help managers keep track of various metrics on their instance. Probably the closest thing to what you're looking for could be achieved by using a content drilldown view with GA. There's unfortunately not a way to share those views to an external site, but you personally could keep track of what books have the most activity (page views, unique page view or other metric) through google analytics.

**Comment by johnpeterm** [comment]
Thank you for sharing an idea to track most read book  privately through GA.
